In [2]:
#Syntax---- varname=numpy.eye(N.M=None,k=0,dtype)
#Generates Unit OR Identity Matrix within Square OR Rectagle Matrix

In [3]:
#Create an Object Using eye()
import numpy as np
a=np.eye(3)
print("Identity Matrix={} Type={}".format(a,type(a)))
print("Dimension of a={}".format(a.ndim))

Identity Matrix=[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] Type=<class 'numpy.ndarray'>
Dimension of a=2


In [4]:
#Create an Object Using eye()
import numpy as np
a=np.eye(3,dtype=int)
print("Identity Matrix={} Type={}".format(a,type(a)))
print("Dimension of a={}".format(a.ndim))

Identity Matrix=[[1 0 0]
 [0 1 0]
 [0 0 1]] Type=<class 'numpy.ndarray'>
Dimension of a=2


In [5]:
#Create an Object of eye()
import numpy as np
a=np.eye(6,dtype=int)
print("Identity Matrix={} Type={}".format(a,type(a)))
print("Dimension of a={}".format(a.ndim))

Identity Matrix=[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]] Type=<class 'numpy.ndarray'>
Dimension of a=2


In [7]:
#Create an Object of eye()
import numpy as np
a=np.eye(3,k=-1,dtype=int)
print("Identity Matrix={} Type={}".format(a,type(a)))
print("Dimension of a={}".format(a.ndim))

Identity Matrix=[[0 0 0]
 [1 0 0]
 [0 1 0]] Type=<class 'numpy.ndarray'>
Dimension of a=2


In [8]:
#Create an Object of eye()
import numpy as np
a=np.eye(3,k=1,dtype=int)
print("Identity Matrix={} Type={}".format(a,type(a)))
print("Dimension of a={}".format(a.ndim))

Identity Matrix=[[0 1 0]
 [0 0 1]
 [0 0 0]] Type=<class 'numpy.ndarray'>
Dimension of a=2


In [11]:
#Create an Object of eye()
import numpy as np
a=np.eye(3,k=-2,dtype=int)
print("Identity Matrix={} Type={}".format(a,type(a)))
print("Dimension of a={}".format(a.ndim))

Identity Matrix=[[0 0 0]
 [0 0 0]
 [1 0 0]] Type=<class 'numpy.ndarray'>
Dimension of a=2


In [12]:
#Create an Object of eye()
import numpy as np
a=np.eye(6,k=-1,dtype=int)
print("Identity Matrix={} Type={}".format(a,type(a)))
print("Dimension of a={}".format(a.ndim))

Identity Matrix=[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]] Type=<class 'numpy.ndarray'>
Dimension of a=2


In [14]:
#Create an Object of eye()
import numpy as np
a=np.eye(7,k=-4,dtype=int)
print("Identity Matrix={} Type={}".format(a,type(a)))
print("Dimension of a={}".format(a.ndim))

Identity Matrix=[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]] Type=<class 'numpy.ndarray'>
Dimension of a=2


In [15]:
#Create an Object of eye()
import numpy as np
a=np.eye(7,k=4,dtype=int)
print("Identity Matrix={} Type={}".format(a,type(a)))
print("Dimension of a={}".format(a.ndim))

Identity Matrix=[[0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] Type=<class 'numpy.ndarray'>
Dimension of a=2


In [18]:
#Create an Object of eye()
import numpy as np
a=np.eye(4,3,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dimension of a={}".format(a.ndim))

Identity Matrix
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]] <class 'numpy.ndarray'>
Dimension of a=2


In [19]:
#Create an Object of eye()
import numpy as np
a=np.eye(3,4,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dimension of a={}".format(a.ndim))

Identity Matrix
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]] <class 'numpy.ndarray'>
Dimension of a=2


In [20]:
#Create an Object of eye()
import numpy as np
a=np.eye(3,4,k=-3,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dimension of a={}".format(a.ndim))

Identity Matrix
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] <class 'numpy.ndarray'>
Dimension of a=2


In [21]:
#Create an Object of eye()
import numpy as np
a=np.eye(3,4,k=4,dtype=int)
print("Identity Matrix")
print(a,type(a))
print("Dimension of a={}".format(a.ndim))

Identity Matrix
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] <class 'numpy.ndarray'>
Dimension of a=2
