In [1]:
#Syntax---varname=numpy.hstack( (ndarrayobj1,ndarrayobj2) )

In [7]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Matrix-A")
print(a)
print("Shape of Matrix-A=",a.shape)
b=np.array([[15,25],[35,45],[34,1]])
print("Matrix-B")
print(b)
print("Shape of Matrix-B=",b.shape)

Matrix-A
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape of Matrix-A= (3, 3)
Matrix-B
[[15 25]
 [35 45]
 [34  1]]
Shape of Matrix-B= (3, 2)


In [9]:
#Perform Horizontal Stacking (Consider the Number of Rows)
c=np.hstack((a,b))
print("Matrix-C")
print(c)
print("Shape of Matrix-C=",c.shape)

Matrix-C
[[10 20 30 15 25]
 [40 50 60 35 45]
 [70 80 90 34  1]]
Shape of Matrix-C= (3, 5)


In [10]:
#Perform Horizontal Stacking (Consider the Number of Rows)
d=np.hstack((b,a))
print("Matrix-D")
print(d)
print("Shape of Matrix-D",d.shape)

Matrix-D
[[15 25 10 20 30]
 [35 45 40 50 60]
 [34  1 70 80 90]]
Shape of Matrix-D (3, 5)


In [12]:
#Merging the Two Matrices Using hstack()
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Matrix-A")
print(a)
print("Shape of Matrix-A=",a.shape)
b=np.array([[15,25,35],[45,55,65]])
print("Matrix-B")
print(b)
print("Shape of Matrix-b=",b.shape)
c=np.hstack((a,b))

Matrix-A
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape of Matrix-A= (3, 3)
Matrix-B
[[15 25 35]
 [45 55 65]]
Shape of Matrix-b= (2, 3)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [13]:
#Syntax----varname=numpy.vstack( (ndarrayobj1,ndarrayobj2) )

In [16]:
#Creating Two Matrices 
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Matrix-A")
print(a)
print("Shape of Matrix-A=",a.shape)
b=np.array([[15,25,34],[34,1,55]])
print("Matrix-B")
print(b)
print("Shape of Matrix-B=",b.shape)

Matrix-A
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape of Matrix-A= (3, 3)
Matrix-B
[[15 25 34]
 [34  1 55]]
Shape of Matrix-B= (2, 3)


In [17]:
#Perform Vertical Stacking (Consider the Number of Cols)
c=np.vstack((a,b))
print("Matrix-C")
print(c)
print("Shape of Matrix-C=",c.shape)

Matrix-C
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 25 34]
 [34  1 55]]
Shape of Matrix-C= (5, 3)


In [18]:
#Perform Vertical Stacking (Consider the Number of Cols)
d=np.vstack((b,a))
print("Matrix-D")
print(d)
print("Shape of Matrix-D=",d.shape)

Matrix-D
[[15 25 34]
 [34  1 55]
 [10 20 30]
 [40 50 60]
 [70 80 90]]
Shape of Matrix-D= (5, 3)


In [19]:
#Syntax----varnmae=numpy.diag(ndarray,k)

In [20]:
#Create a Matrix Using diag()
import numpy as np
a=np.arange(9).reshape(3,3)
print("Matrix-A")
print(a)
print("Shape of a={}".format(a.shape))
print("Dimension of a={}".format(a.ndim))

Matrix-A
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Shape of a=(3, 3)
Dimension of a=2


In [21]:
#Get The Principle Diagonal Elements
pd=np.diag(a,0)  -----#k=0
print("Principle Diagonal={} Type={}".format(pd,type(pd)))

Principle Diagonal=[0 4 8] Type=<class 'numpy.ndarray'>


In [22]:
#Get Lower Principle Diagonal Elements
print("Matrix-A")
print(a)
pd=np.diag(a,k=-1)
print("Principle Diagonal={} Type={}".format(pd,type(pd)))

Matrix-A
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Principle Diagonal=[3 7] Type=<class 'numpy.ndarray'>


In [23]:
#Get Lower Principle Diagonal Elements
print("Matrix-A")
print(a)
pd=np.diag(a,k=1)
print("Principle Diagonal={} Type={}".format(pd,type(pd)))

Matrix-A
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Principle Diagonal=[1 5] Type=<class 'numpy.ndarray'>


In [25]:
#Get The Principle Diagonal Elements
print("Matrix-A")
print(a)
pd=np.diag(a)
print("Principle Diagonal={} Type={}".format(pd,type(pd)))

Matrix-A
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Principle Diagonal=[0 4 8] Type=<class 'numpy.ndarray'>
