In [1]:
#By Using Looping Statements To Display the Data of ndarray
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("1-d Array Data={} Dimension={}".format(a,a.ndim))
for val in a:
    print("\t {}".format(val))

1-d Array Data=[10 20 30 40 50 60 70 80 90] Dimension=1
	 10
	 20
	 30
	 40
	 50
	 60
	 70
	 80
	 90


In [4]:
#By Using Looping Statements To Display the Data of ndarray for 2-d
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("2-d Array Data\n{} Dimension={}".format(a,a.ndim))
for row in a:
    for val in row:
        print("\t{}".format(val))

2-d Array Data
[[10 20 30]
 [40 50 60]
 [70 80 90]] Dimension=2
	10
	20
	30
	40
	50
	60
	70
	80
	90


In [7]:
#By Using Looping Statements To Display the Data of ndarray for 3-d
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,34,1,55]).reshape(2,3,2)
print("3-d Array Data\n{} Dimension={}".format(a,a.ndim))
for matrix in a:
    for row in matrix:
        for val in row:
            print("\t{}".format(val))
        print("-------------------------")

3-d Array Data
[[[10 20]
  [30 40]
  [50 60]]

 [[70 80]
  [90 34]
  [ 1 55]]] Dimension=3
	10
	20
-------------------------
	30
	40
-------------------------
	50
	60
-------------------------
	70
	80
-------------------------
	90
	34
-------------------------
	1
	55
-------------------------


In [9]:
#By Using Looping Statements To Display the Data of ndarray for 4-d
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,34,1,55,16,18,19,11]).reshape(2,2,2,2)
print("4-d Array Data\n{} Dimension={}".format(a,a.ndim))
for cluster in a:
    for matrix in cluster:
        for row in matrix:
            for val in row:
                print("\t {}".format(val))

4-d Array Data
[[[[10 20]
   [30 40]]

  [[50 60]
   [70 80]]]


 [[[90 34]
   [ 1 55]]

  [[16 18]
   [19 11]]]] Dimension=4
	 10
	 20
	 30
	 40
	 50
	 60
	 70
	 80
	 90
	 34
	 1
	 55
	 16
	 18
	 19
	 11


In [10]:
#By Using numpy.nditer()

In [11]:
#By Using numpy.nditer() To Display the Data of ndarray for 1-d
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("1-d Array Data={} Dimension={}".format(a,a.ndim))
for val in np.nditer(a):
    print("\t {}".format(val))

1-d Array Data=[10 20 30 40 50 60 70 80 90] Dimension=1
	 10
	 20
	 30
	 40
	 50
	 60
	 70
	 80
	 90


In [12]:
#By Using numpy.nditer() To Display the Data of ndarray for 2-d
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("2-d Array Data\n{} Dimension={}".format(a,a.ndim))
for val in np.nditer(a):
    print("\t {}".format(val))

2-d Array Data
[[10 20 30]
 [40 50 60]
 [70 80 90]] Dimension=2
	 10
	 20
	 30
	 40
	 50
	 60
	 70
	 80
	 90


In [13]:
#By Using numpy.nditer() To Display the Data of ndarray for 3-d
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,34,1,55]).reshape(2,3,2)
print("3-d Array Data\n{} Dimension={}".format(a,a.ndim))
for val in np.nditer(a):
    print("\t {}".format(val))

3-d Array Data
[[[10 20]
  [30 40]
  [50 60]]

 [[70 80]
  [90 34]
  [ 1 55]]] Dimension=3
	 10
	 20
	 30
	 40
	 50
	 60
	 70
	 80
	 90
	 34
	 1
	 55


In [14]:
#By Using numpy.nditer() To Display the Data of ndarray for 4-d
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,34,1,55,16,18,19,11]).reshape(2,2,2,2)
print("4-d Array Data\n{} Dimension={}".format(a,a.ndim))
for val in np.nditer(a):
    print("\t {}".format(val))

4-d Array Data
[[[[10 20]
   [30 40]]

  [[50 60]
   [70 80]]]


 [[[90 34]
   [ 1 55]]

  [[16 18]
   [19 11]]]] Dimension=4
	 10
	 20
	 30
	 40
	 50
	 60
	 70
	 80
	 90
	 34
	 1
	 55
	 16
	 18
	 19
	 11


In [15]:
#By Using numpy.ndenumerate()

In [16]:
#By Using numpy.ndenumerate() To Display the Data of ndarray for 1-d
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("1-d Array Data={} Dimension={}".format(a,a.ndim))
for val in np.ndenumerate(a):
    print("\t {}".format(val))

1-d Array Data=[10 20 30 40 50 60 70 80 90] Dimension=1
	 ((0,), np.int64(10))
	 ((1,), np.int64(20))
	 ((2,), np.int64(30))
	 ((3,), np.int64(40))
	 ((4,), np.int64(50))
	 ((5,), np.int64(60))
	 ((6,), np.int64(70))
	 ((7,), np.int64(80))
	 ((8,), np.int64(90))


In [17]:
#By Using numpy.ndenumerate() To Display the Data of ndarray for 1-d
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("1-d Array Data={} Dimension={}".format(a,a.ndim))
for val in np.ndenumerate(a):
    print("\t {}--->{}".format(val[0],val[1]))

1-d Array Data=[10 20 30 40 50 60 70 80 90] Dimension=1
	 (0,)--->10
	 (1,)--->20
	 (2,)--->30
	 (3,)--->40
	 (4,)--->50
	 (5,)--->60
	 (6,)--->70
	 (7,)--->80
	 (8,)--->90


In [19]:
#By Using numpy.ndenumerate() To Display the Data of ndarray for 1-d
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("1-d Array Data={} Dimension={}".format(a,a.ndim))
for val in np.ndenumerate(a):
    print("\t {}---->{}".format(val[0][0],val[1]))

1-d Array Data=[10 20 30 40 50 60 70 80 90] Dimension=1
	 0---->10
	 1---->20
	 2---->30
	 3---->40
	 4---->50
	 5---->60
	 6---->70
	 7---->80
	 8---->90


In [23]:
#By Using numpy.ndenumerate() To Display the Data of ndarray for 2-d
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("2-d Array Data\n{} Dimension={}".format(a,a.ndim))
for val in np.ndenumerate(a):
    print("{}".format(val))

2-d Array Data
[[10 20 30]
 [40 50 60]
 [70 80 90]] Dimension=2
((0, 0), np.int64(10))
((0, 1), np.int64(20))
((0, 2), np.int64(30))
((1, 0), np.int64(40))
((1, 1), np.int64(50))
((1, 2), np.int64(60))
((2, 0), np.int64(70))
((2, 1), np.int64(80))
((2, 2), np.int64(90))


In [24]:
#By Using numpy.ndenumerate() To Display the Data of ndarray for 2-d
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("2-d Array Data\n{} Dimension={}".format(a,a.ndim))
for val in np.ndenumerate(a):
    print("\t {}---->{}".format(val[0],val[1]))

2-d Array Data
[[10 20 30]
 [40 50 60]
 [70 80 90]] Dimension=2
	 (0, 0)---->10
	 (0, 1)---->20
	 (0, 2)---->30
	 (1, 0)---->40
	 (1, 1)---->50
	 (1, 2)---->60
	 (2, 0)---->70
	 (2, 1)---->80
	 (2, 2)---->90


In [28]:
#By Using numpy.ndenumerate() To Display the Data of ndarray for 2-d
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("2-d Array Data\n{} Dimension={}".format(a,a.ndim))
for val in np.ndenumerate(a):
    print("\tRow:{}, Column:{}---->value:{}".format(val[0][0],val[0][1],val[1]))

2-d Array Data
[[10 20 30]
 [40 50 60]
 [70 80 90]] Dimension=2
	Row:0, Column:0---->value:10
	Row:0, Column:1---->value:20
	Row:0, Column:2---->value:30
	Row:1, Column:0---->value:40
	Row:1, Column:1---->value:50
	Row:1, Column:2---->value:60
	Row:2, Column:0---->value:70
	Row:2, Column:1---->value:80
	Row:2, Column:2---->value:90


In [31]:
#By Using numpy.ndenumerate() To Display the Data of ndarray for 3-d
import numpy as np
a=np.array([10,20,30,40,50,60,70,80]).reshape(2,2,2)
print("3-d Array Data\n{} Dimension={}".format(a,a.ndim))
for val in np.ndenumerate(a):
    print("{}".format(val))

3-d Array Data
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]] Dimension=3
((0, 0, 0), np.int64(10))
((0, 0, 1), np.int64(20))
((0, 1, 0), np.int64(30))
((0, 1, 1), np.int64(40))
((1, 0, 0), np.int64(50))
((1, 0, 1), np.int64(60))
((1, 1, 0), np.int64(70))
((1, 1, 1), np.int64(80))


In [33]:
#By Using numpy.ndenumerate() To Display the Data of ndarray for 3-d
import numpy as np
a=np.array([10,20,30,40,50,60,70,80]).reshape(2,2,2)
print("3-d Array Data\n{} Dimension={}".format(a,a.ndim))
for val in np.ndenumerate(a):
    print("\t Matrix:{} Row:{} Column:{} Value:{}".format(val[0][0],val[0][1],val[0][2],val[1]))

3-d Array Data
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]] Dimension=3
	 Matrix:0 Row:0 Column:0 Value:10
	 Matrix:0 Row:0 Column:1 Value:20
	 Matrix:0 Row:1 Column:0 Value:30
	 Matrix:0 Row:1 Column:1 Value:40
	 Matrix:1 Row:0 Column:0 Value:50
	 Matrix:1 Row:0 Column:1 Value:60
	 Matrix:1 Row:1 Column:0 Value:70
	 Matrix:1 Row:1 Column:1 Value:80


In [35]:
#By Using numpy.ndenumerate() To Display the Data of ndarray for 3-d
import numpy as np
a=np.arange(2*3*3).reshape(2,3,3)
print("3-d Array Data\n{} Dimension={}".format(a,a.ndim))
for val in np.ndenumerate(a):
    print("\t Matrix:{} Row:{} Column:{} Value:{}".format(val[0][0],val[0][1],val[0][2],val[1]))

3-d Array Data
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]] Dimension=3
	 Matrix:0 Row:0 Column:0 Value:0
	 Matrix:0 Row:0 Column:1 Value:1
	 Matrix:0 Row:0 Column:2 Value:2
	 Matrix:0 Row:1 Column:0 Value:3
	 Matrix:0 Row:1 Column:1 Value:4
	 Matrix:0 Row:1 Column:2 Value:5
	 Matrix:0 Row:2 Column:0 Value:6
	 Matrix:0 Row:2 Column:1 Value:7
	 Matrix:0 Row:2 Column:2 Value:8
	 Matrix:1 Row:0 Column:0 Value:9
	 Matrix:1 Row:0 Column:1 Value:10
	 Matrix:1 Row:0 Column:2 Value:11
	 Matrix:1 Row:1 Column:0 Value:12
	 Matrix:1 Row:1 Column:1 Value:13
	 Matrix:1 Row:1 Column:2 Value:14
	 Matrix:1 Row:2 Column:0 Value:15
	 Matrix:1 Row:2 Column:1 Value:16
	 Matrix:1 Row:2 Column:2 Value:17


In [37]:
#By Using numpy.ndenumerate() To Display the Data of ndarray for 4-d
import numpy as np
a=np.arange(2*2*3*3).reshape(2,2,3,3)
print("4-d Array Data\n{} Dimension={}".format(a,a.ndim))
for val in np.ndenumerate(a):
    print("\t Cluster:{} Matrix:{} Row:{} Column:{}---->Value:{}".format(val[0][0],val[0][1],val[0][2],val[0][3],val[1]))

4-d Array Data
[[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]]

  [[ 9 10 11]
   [12 13 14]
   [15 16 17]]]


 [[[18 19 20]
   [21 22 23]
   [24 25 26]]

  [[27 28 29]
   [30 31 32]
   [33 34 35]]]] Dimension=4
	 Cluster:0 Matrix:0 Row:0 Column:0---->Value:0
	 Cluster:0 Matrix:0 Row:0 Column:1---->Value:1
	 Cluster:0 Matrix:0 Row:0 Column:2---->Value:2
	 Cluster:0 Matrix:0 Row:1 Column:0---->Value:3
	 Cluster:0 Matrix:0 Row:1 Column:1---->Value:4
	 Cluster:0 Matrix:0 Row:1 Column:2---->Value:5
	 Cluster:0 Matrix:0 Row:2 Column:0---->Value:6
	 Cluster:0 Matrix:0 Row:2 Column:1---->Value:7
	 Cluster:0 Matrix:0 Row:2 Column:2---->Value:8
	 Cluster:0 Matrix:1 Row:0 Column:0---->Value:9
	 Cluster:0 Matrix:1 Row:0 Column:1---->Value:10
	 Cluster:0 Matrix:1 Row:0 Column:2---->Value:11
	 Cluster:0 Matrix:1 Row:1 Column:0---->Value:12
	 Cluster:0 Matrix:1 Row:1 Column:1---->Value:13
	 Cluster:0 Matrix:1 Row:1 Column:2---->Value:14
	 Cluster:0 Matrix:1 Row:2 Column:0---->Value:15
	 Cluster:0 Matrix:1