In [1]:
#Using arange()----varname=numpy.arange(Value)
import numpy as np
a=np.arange(10)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of ndarray={}".format(a.ndim))
print("Shape of ndarray={}".format(a.shape))
print("Size of ndarray={}".format(a.size))

Content of a=[0 1 2 3 4 5 6 7 8 9] Type=<class 'numpy.ndarray'>
Dimension of ndarray=1
Shape of ndarray=(10,)
Size of ndarray=10


In [2]:
#Using arange()----varname=numpy.arange(Value)----2D
import numpy as np
a=np.arange(10).reshape(5,2)
print("content of a\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  
print("Shape of ndarray={}".format(a.shape))   
print("Size of ndarray={}".format(a.size)) 

content of a
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =2
Shape of ndarray=(5, 2)
Size of ndarray=10


In [4]:
#Using arange()----varname=numpy.arange(Value)----3D
import numpy as np
a=np.arange(12).reshape(2,3,2)
print("content of a\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  
print("Shape of ndarray={}".format(a.shape))   
print("Size of ndarray={}".format(a.size)) 

content of a
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =3
Shape of ndarray=(2, 3, 2)
Size of ndarray=12


In [5]:
#Using arange()----varname=numpy.arange(Value)----4D
import numpy as np
a=np.arange(16).reshape(2,2,2,2)
print("content of a\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  
print("Shape of ndarray={}".format(a.shape))   
print("Size of ndarray={}".format(a.size)) 

content of a
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =4
Shape of ndarray=(2, 2, 2, 2)
Size of ndarray=16


In [6]:
#Using arange()----varname=numpy.arange(Value)
import numpy as np
a=np.arange(10,21,2)
print("content of a\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  
print("Shape of ndarray={}".format(a.shape))   
print("Size of ndarray={}".format(a.size)) 

content of a
[10 12 14 16 18 20]  Type=<class 'numpy.ndarray'>
Dimension ndarray =1
Shape of ndarray=(6,)
Size of ndarray=6


In [7]:
#Using arange()----varname=numpy.arange(Value)---2D
import numpy as np
a=np.arange(10,21,2).reshape(2,3)
print("content of a\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  
print("Shape of ndarray={}".format(a.shape))  
print("Size of ndarray={}".format(a.size)) 

content of a
[[10 12 14]
 [16 18 20]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =2
Shape of ndarray=(2, 3)
Size of ndarray=6


In [10]:
#Using arange()----varname=numpy.arange(Value)
import numpy as np
a=np.arange(10,21,0.5)
print("content of a\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  
print("Shape of ndarray={}".format(a.shape))  
print("Size of ndarray={}".format(a.size)) 
print("Data Type Element of ndarray={}".format(a.dtype))

content of a
[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5]  Type=<class 'numpy.ndarray'>
Dimension ndarray =1
Shape of ndarray=(22,)
Size of ndarray=22
Data Type Element of ndarray=float64


In [11]:
#Using arange()----varname=numpy.arange(Value)----2D
import numpy as np
a=np.arange(10,21,0.5).reshape(11,2)
print("content of a\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))  
print("Shape of ndarray={}".format(a.shape))  
print("Size of ndarray={}".format(a.size)) 
print("Data Type Element of ndarray={}".format(a.dtype))

content of a
[[10.  10.5]
 [11.  11.5]
 [12.  12.5]
 [13.  13.5]
 [14.  14.5]
 [15.  15.5]
 [16.  16.5]
 [17.  17.5]
 [18.  18.5]
 [19.  19.5]
 [20.  20.5]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =2
Shape of ndarray=(11, 2)
Size of ndarray=22
Data Type Element of ndarray=float64
