In [1]:
#Creating an Object of ndarray Using array() 
import numpy as np
a=10
print("Content of a={} Type={}".format(a,type(a)))
a1=np.array(a)
print("Content of ndarray={} Type={}".format(a1,type(a1)))
print("Dimension of ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndarray={}".format(a1.size))

Content of a=10 Type=<class 'int'>
Content of a1=10 Type=<class 'numpy.ndarray'>
Dimension of ndarray=0
Shape of ndarray=()
Size of ndarray=1


In [2]:
#Creating an Object of ndarray Using array() 
import numpy as np
a=34.0
print("Content of a={} Type={}".format(a,type(a)))
a1=np.array(a)
print("Content of ndarray={} Type={}".format(a1,type(a1)))
print("Dimension of ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndarray={}".format(a1.size))

Content of a=34.0 Type=<class 'float'>
Content of a1=34.0 Type=<class 'numpy.ndarray'>
Dimension of ndarray=0
Shape of ndarray=()
Size of ndarray=1


In [4]:
#Creating an Object of ndarray Using array()
import numpy as np
a=True
print("Content of a={} Type={}".format(a,type(a)))
a1=np.array(a)
print("Content of ndarray={} Type={}".format(a1,type(a1)))
print("Dimension of ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndarray={}".format(a1.size))

Content of a=True Type=<class 'bool'>
Content of a1=True Type=<class 'numpy.ndarray'>
Dimension of ndarray=0
Shape of ndarray=()
Size of ndarray=1


In [5]:
#Creating an Object of ndarray Using array()
import numpy as np
a=2+3j
print("Content of a={} Type={}".format(a,type(a)))
a1=np.array(a)
print("Content of ndarray={} Type={}".format(a1,type(a1)))
print("Dimension of ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndarray={}".format(a1.size))

Content of a=(2+3j) Type=<class 'complex'>
Content of a1=(2+3j) Type=<class 'numpy.ndarray'>
Dimension of ndarray=0
Shape of ndarray=()
Size of ndarray=1


In [6]:
#Creating an Object of ndarray Using array()
import numpy as np
a="PYTHON"
print("Content of a={} Type={}".format(a,type(a)))
a1=np.array(a)
print("Content of ndarray={} Type={}".format(a1,type(a1)))
print("Dimension of ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndrray={}".format(a1.size))

Content of a=PYTHON Type=<class 'str'>
Content of a1=PYTHON Type=<class 'numpy.ndarray'>
Dimension of ndarray=0
Shape of ndarray=()
Size of ndrray=1


In [7]:
#Creating an Object of ndarray Using array()
import numpy as np
a=range(10,21,2)
print("Content of a={} Type={}".format(a,type(a)))
a1=np.array(a)
print("Content of ndarray={} Type={}".format(a1,type(a1)))
print("Dimension of ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndarray={}".format(a1.size))

Content of a=range(10, 21, 2) Type=<class 'range'>
Content of a1=[10 12 14 16 18 20] Type=<class 'numpy.ndarray'>
Dimension of ndarray=1
Shape of ndarray=(6,)
Size of ndarray=6


In [8]:
#Creating an Object of ndarray Using array()
import numpy as np 
a=range(10,0,-2)
print("Content of a={} Type={}".format(a,type(a)))
a1=np.array(a)
print("Content of ndarray={} Type={}".format(a1,type(a1)))
print("Dimension of ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndarray={}".format(a1.size))

Content of a=range(10, 0, -2) Type=<class 'range'>
Content of a1=[10  8  6  4  2] Type=<class 'numpy.ndarray'>
Dimension of ndarray=1
Shape of ndarray=(5,)
Size of ndarray=5


In [9]:
#Creating an Object of ndarray Using array()
import numpy as np
a=range(0,9)
print("Content of a={} Type={}".format(a,type(a)))
a1=np.array(a)
print("Content of ndarray={} Type={}".format(a1,type(a1)))
print("Dimension of ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndarray={}".format(a1.size))

Content of a=range(0, 9) Type=<class 'range'>
Content of a1=[0 1 2 3 4 5 6 7 8] Type=<class 'numpy.ndarray'>
Dimension of ndarray=1
Shape of ndarray=(9,)
Size of ndarray=9


In [12]:
#Re-Shape an Object of ndarray --- By Using Shape Attribute
a1.shape=(3,3)
print("Content of ndarray={} Type={}".format(a1,type(a1)))
print("Dimension of ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndarray={}".format(a1.size))

Content of ndarray=[[0 1 2]
 [3 4 5]
 [6 7 8]] Type=<class 'numpy.ndarray'>
Dimension of ndarray=2
Shape of ndarray=(3, 3)
Size of ndarray=9


In [13]:
#Creating an Object of ndarray Using array() --- 2 Dimension
import numpy as np 
a=range(0,16)
print("Content of a={} Type={}".format(a,type(a)))
a1=np.array(a)
a1.shape=(4,4)  #Use Shape Attribute to Change the Dimension
print("Content of ndarray={} Type={}".format(a1,type(a1)))
print("Dimension of ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndarray={}".format(a1.size))

Content of a=range(0, 16) Type=<class 'range'>
Content of ndarray=[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] Type=<class 'numpy.ndarray'>
Dimension of ndarray=2
Shape of ndarray=(4, 4)
Size of ndarray=16


In [14]:
#Creating an Object of ndarray Using array() ---- 3 Dimension
import numpy as np
a=range(0,16)
print("Content of a={} Type={}".format(a,type(a)))
a1=np.array(a)
a1.shape=(2,4,2)   #USe Shape Attribute to Change The Dimension
print("Content of ndarray={} Type={}".format(a1,type(a1)))
print("Dimension of ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndarray={}".format(a1.size))

Content of a=range(0, 16) Type=<class 'range'>
Content of ndarray=[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]] Type=<class 'numpy.ndarray'>
Dimension of ndarray=3
Shape of ndarray=(2, 4, 2)
Size of ndarray=16


In [15]:
#Creating an Object of ndarray Using array() --- 4 Dimension
import numpy as np
a=range(0,16)
print("Content of a={} Type={}".format(a,type(a)))
a1=np.array(a)
a1.shape=(2,2,2,2)
print("Content of ndarray={} Type={}".format(a1,type(a1)))
print("Dimension of ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndarray={}".format(a1.size))

Content of a=range(0, 16) Type=<class 'range'>
Content of ndarray=[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]] Type=<class 'numpy.ndarray'>
Dimension of ndarray=4
Shape of ndarray=(2, 2, 2, 2)
Size of ndarray=16


In [16]:
#Creating an Object of ndarray Using array() --- 2D
import numpy as np
a=range(24)
print("Content of a={} Type={}".format(a,type(a)))
a1=np.array(a)
a1.shape=(6,4)
print("Content of ndarray={} Type={}".format(a1,type(a1)))
print("Dimension of ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndarray={}".format(a1.size))

Content of a=range(0, 24) Type=<class 'range'>
Content of ndarray=[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] Type=<class 'numpy.ndarray'>
Dimension of ndarray=2
Shape of ndarray=(6, 4)
Size of ndarray=24


In [2]:
#Creating an Object of ndarray Using array() --- dtype
import numpy as np
a=range(24)
print("Content of a={} Type={}".format(a,type(a)))
a1=np.array(a)
a1.shape=(6,4)
print("Content of ndarray={} Type={}".format(a1,type(a1)))
print("Dimension of ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndarray={}".format(a1.size))
print("Data Type Elements of ndarray={}".format(a1.dtype))

Content of a=range(0, 24) Type=<class 'range'>
Content of ndarray=[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] Type=<class 'numpy.ndarray'>
Dimension of ndarray=2
Shape of ndarray=(6, 4)
Size of ndarray=24
Data Type Elements of ndarray=int64


In [4]:
#Creating an Object of ndarray Using array()---Converting int to float type
import numpy as np
a=range(24)
print("Content of ndarray={} Type={}".format(a,type(a)))
a1=np.array(a,dtype=float)  #Convert to Float type
a1.shape=(6,4)
print("Content of ndarray={} Type={}".format(a1,type(a1)))
print("Dimension of ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndarray={}".format(a1.size))
print("Data Type Elements of ndarray={}".format(a1.dtype))

Content of ndarray=range(0, 24) Type=<class 'range'>
Content of ndarray=[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]] Type=<class 'numpy.ndarray'>
Dimension of ndarray=2
Shape of ndarray=(6, 4)
Size of ndarray=24
Data Type Elements of ndarray=float64


In [5]:
#Creating an Object of ndarray Using array()----list datatype
import numpy as np
lst=[10,20,30,40,50,60]
print("Content of lst={} Type={}".format(lst,type(lst)))
a=np.array(lst)
print("Content of ndarray={} Type={}".format(a,type(a)))
print("Dimension of ndarray={}".format(a.ndim))
print("Shape of ndarray={}".format(a.shape))
print("Size of ndarray={}".format(a.size))
print("Data Type Elements of ndarray={}".format(a.dtype))

Content of lst=[10, 20, 30, 40, 50, 60] Type=<class 'list'>
Content of ndarray=[10 20 30 40 50 60] Type=<class 'numpy.ndarray'>
Dimension of ndarray=1
Shape of ndarray=(6,)
Size of ndarray=6
Data Type Elements of ndarray=int64


In [6]:
#Creating an Object of ndarray Using array()---dtype
import numpy as np
lst=[10,20,30,40,50,60]
print("Content of lst={} Type={}".format(lst,type(lst)))
a=np.array(lst,float).reshape(3,2)
print("Content of ndarray={} Type={}".format(a,type(a)))
print("Dimension of ndarray={}".format(a.ndim))
print("Shape of ndarray={}".format(a.shape))
print("Size of ndarray={}".format(a.size))
print("Data Type Elements of ndarray={}".format(a.dtype))

Content of lst=[10, 20, 30, 40, 50, 60] Type=<class 'list'>
Content of ndarray=[[10. 20.]
 [30. 40.]
 [50. 60.]] Type=<class 'numpy.ndarray'>
Dimension of ndarray=2
Shape of ndarray=(3, 2)
Size of ndarray=6
Data Type Elements of ndarray=float64


In [7]:
#Creating an Object of ndarray Using array()---float()
import numpy as np
lst=[[10,20],[30,40],[50,60],[70,80]]
print("Content of lst={} Type={}".format(lst,type(lst)))
a=np.array(lst,float)
print("Content of ndarray={} Type={}".format(a,type(a)))
print("Dimension of ndarray={}".format(a.ndim))
print("Shape of ndarray={}".format(a.shape))
print("Size of ndarray={}".format(a.size))
print("Data Type Elements of ndarray={}".format(a.dtype))

Content of lst=[[10, 20], [30, 40], [50, 60], [70, 80]] Type=<class 'list'>
Content of ndarray=[[10. 20.]
 [30. 40.]
 [50. 60.]
 [70. 80.]] Type=<class 'numpy.ndarray'>
Dimension of ndarray=2
Shape of ndarray=(4, 2)
Size of ndarray=8
Data Type Elements of ndarray=float64


In [8]:
#Creating an Objct of ndarray Using array()----Nested List
import numpy as np
lst=[[[10,20],[30,40]],[[50,60],[70,80]]]
print("Content of list={}  Type list={}".format(lst,type(lst)))
a=np.array(lst,float)
print("Content of ndarray\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))
print("Shape of ndarray={}".format(a.shape)) 
print("Size of ndarray={}".format(a.size)) 
print("Data type Elements of ndarray={}".format(a.dtype)) 

Content of list=[[[10, 20], [30, 40]], [[50, 60], [70, 80]]]  Type list=<class 'list'>
Content of ndarray
[[[10. 20.]
  [30. 40.]]

 [[50. 60.]
  [70. 80.]]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =3
Shape of ndarray=(2, 2, 2)
Size of ndarray=8
Data type Elements of ndarray=float64


In [9]:
#Creating an Object of ndarray Using array()----List in tuple
import numpy as np
lst=(([10,20],[30,40]),([50,60],[70,80]))
print("Content of list={}  Type list={}".format(lst,type(lst)))
a=np.array(lst,float)
print("Content of ndarray\n{}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))
print("Shape of ndarray={}".format(a.shape))
print("Size of ndarray={}".format(a.size)) 
print("Data type Elements of ndarray={}".format(a.dtype))

Content of list=(([10, 20], [30, 40]), ([50, 60], [70, 80]))  Type list=<class 'tuple'>
Content of ndarray
[[[10. 20.]
  [30. 40.]]

 [[50. 60.]
  [70. 80.]]]  Type=<class 'numpy.ndarray'>
Dimension ndarray =3
Shape of ndarray=(2, 2, 2)
Size of ndarray=8
Data type Elements of ndarray=float64


In [10]:
#Creating an Object of ndarray Using array()----set()
import numpy as np
s1={10,20,30,40,50,60,70,80,90}
print("Content of s1={}  Type s1={}".format(s1,type(s1)))
a=np.array(s1)
print("Content of ndarray={}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))    
print("Shape of ndarray={}".format(a.shape))     
print("Size of ndarray={}".format(a.size)) 
print("Data type Elements of ndarray={}".format(a.dtype)) 

Content of s1={70, 40, 10, 80, 50, 20, 90, 60, 30}  Type s1=<class 'set'>
Content of ndarray={70, 40, 10, 80, 50, 20, 90, 60, 30}  Type=<class 'numpy.ndarray'>
Dimension ndarray =0
Shape of ndarray=()
Size of ndarray=1
Data type Elements of ndarray=object


In [11]:
#Creating an Object of ndarray Using array()----dict()
import numpy as np
s1={1:"PYTHON",2:"C",3:"C++",4:"Java"}
print("Content of s1={}  Type s1={}".format(s1,type(s1)))
a=np.array(s1)
print("Content of ndarray={}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))    
print("Shape of ndarray={}".format(a.shape))     
print("Size of ndarray={}".format(a.size)) 
print("Data type Elements of ndarray={}".format(a.dtype)) 

Content of s1={1: 'PYTHON', 2: 'C', 3: 'C++', 4: 'Java'}  Type s1=<class 'dict'>
Content of ndarray={1: 'PYTHON', 2: 'C', 3: 'C++', 4: 'Java'}  Type=<class 'numpy.ndarray'>
Dimension ndarray =0
Shape of ndarray=()
Size of ndarray=1
Data type Elements of ndarray=object


In [12]:
#Creating an Object of ndarray Using array()----None Type()|
import numpy as np
s1=None
print("Content of s1={}  Type s1={}".format(s1,type(s1)))
a=np.array(s1)
print("Content of ndarray={}  Type={}".format(a,type(a)))
print("Dimension ndarray ={}".format(a.ndim))    
print("Shape of ndarray={}".format(a.shape))     
print("Size of ndarray={}".format(a.size)) 
print("Data type Elements of ndarray={}".format(a.dtype)) 

Content of s1=None  Type s1=<class 'NoneType'>
Content of ndarray=None  Type=<class 'numpy.ndarray'>
Dimension ndarray =0
Shape of ndarray=()
Size of ndarray=1
Data type Elements of ndarray=object
