In [1]:
#Numpy--Indexing Operation

In [2]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("Content of ndarray")
print(a)
print("Dimension of ndarray={} Shape={}".format(a.ndim,a.shape))

Content of ndarray
[10 20 30 40 50 60 70 80 90]
Dimension of ndarray=1 Shape=(9,)


In [3]:
#Indexing Operation  on 1D

In [4]:
#Get 30 Element from 1dArray
print(a[2])

30


In [5]:
#Get 90 Element from 1darray with +VE Index
print(a[len(a)-1])

90


In [6]:
#Get 90 Element from 1darray with +VE Index
print(a[a.size-1])

90


In [8]:
#Get The Element 10 From 1-d Array
print(a[0])

10


In [9]:
print(a)

[10 20 30 40 50 60 70 80 90]


In [10]:
#Get the Element 90 with -VE Index
print(a[-1])

90


In [11]:
#Get the Element 10 with -VE Index
print(a[-a.size])

10


In [12]:
#Get the Element 10 with -VE Index
print(a[-len(a)])

10


In [13]:
#Indexing Operation  on 2D

In [14]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Content of ndarray")
print(a)
print("Dimension of ndarray a={}".format(a.ndim))
print("Shape of ndarray a={}".format(a.shape))

Content of ndarray
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of ndarray a=2
Shape of ndarray a=(3, 3)


In [15]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(9,1)
print("Content of ndarray")
print(a)
print("Dimension of ndarray={}".format(a.ndim))
print("Shape of ndarray={}".format(a.shape))

Content of ndarray
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]]
Dimension of ndarray=2
Shape of ndarray=(9, 1)


In [16]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(1,9)
print("Content of ndarray")
print(a)
print("Dimension of ndarray={}".format(a.ndim))
print("Shape of ndarray={}".format(a.shape))

Content of ndarray
[[10 20 30 40 50 60 70 80 90]]
Dimension of ndarray=2
Shape of ndarray=(1, 9)


In [17]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(9,)
print("Content of ndarray")
print(a)
print("Dimension of ndarray={}".format(a.ndim))
print("Shape of ndarray={}".format(a.shape))

Content of ndarray
[10 20 30 40 50 60 70 80 90]
Dimension of ndarray=1
Shape of ndarray=(9,)


In [18]:
#Indexing Operation  on 2D
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Content of ndarray")
print(a)
print("Dimension of ndarray={}".format(a.ndim))
print("Shape of ndarray={}".format(a.shape))

Content of ndarray
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of ndarray=2
Shape of ndarray=(3, 3)


In [19]:
#Get an Element 50 from 2DArray
print(a[1,1])

50


In [20]:
#Get an Element 50 from 2DArray --- Another Model
print(a[1][1])

50


In [21]:
#Get an Element 50 from 2DArray --- Another Model
print(a[-2,-2])

50


In [22]:
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [23]:
#Get An Element 30 from 2DArray
print(a[0,2])

30


In [24]:
#Get An Element 30 from 2DArray --- Another Model
print(a[0][2])

30


In [28]:
#Indexing Operation  on 3D
import numpy as np
a=np.arange(3*3*3).reshape(3,3,3)
print("Content of ndarray\n{}".format(a))
print("Dimension of ndarray={}".format(a.ndim))
print("Shape of ndarray={}".format(a.shape))

Content of ndarray
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dimension of ndarray=3
Shape of ndarray=(3, 3, 3)


In [29]:
#Get First Matrix From 3D
print(a[0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [30]:
#Get Second Matrix From 3D
print(a[1])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [31]:
#Get Third Matrix From 3D
print(a[-3])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [33]:
#Get 13 from 3D Array
print(a[1,1,1])

13


In [34]:
#Get 13 from 3D Array----Another Model
print(a[1][1][1])

13


In [35]:
#Get 13 from 3D Array-----Another Model
print(a[1,1][1])

13


In [36]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [38]:
#Get Element 26 of 3D with -VE Indices
print(a[-1][-1][-1])

26


In [41]:
#Get Element 26 of 3D with -VE Indices
print(a[-1][-3][-2])

19
