In [5]:
#Numpy---Filtering the Data from ndarray

In [6]:
#Create 1D Array with Random 12 Integer Values
from numpy import random as r
a=r.randint(25,55,size=12)
print("Random Elements={}".format(a))

Random Elements=[26 33 34 40 49 31 42 39 25 45 53 29]


In [9]:
#Get the Factors of 5 --Normal Python Code
lst=[]  #Empty List
for val in a:
    if (val%5==0):
        lst.append(int(val))
print("Factors of 5=",lst)

Factors of 5= [40, 25, 45]


In [13]:
#Get the Factors of 5 --Normal Python Code---List Comprehension
lst=[int(val) for val in a if(val%5==0)]
print("Factors of 5=",lst)

Factors of 5= [40, 25, 45]


In [14]:
#Create 1D Array with Random 12 Integer Values
from numpy import random as r
a=r.randint(25,55,size=12)
print("Random Elements={}".format(a))

Random Elements=[47 38 48 36 42 45 54 32 28 45 35 45]


In [15]:
#Get all Factors of 5
#Step-1: Prepare the Condition with ndarray object
ba=a%5==0
print("Boolean Array={} Type={}".format(ba,type(ba)))
#Step-2: Pass the Boolean Array to the ndarray Object
print("Factors of 5")
print(a[ba])

Boolean Array=[False False False False False  True False False False  True  True  True] Type=<class 'numpy.ndarray'>
Factors of 5
[45 45 35 45]


In [16]:
#Create 1D Array with Random 12 Integer Values
from numpy import random as r
a=r.randint(25,55,size=12)
print("Random Elements")
print(a)
#Get All Factors of 3
#Step-1: Prepare the Condition with ndarray Object
ba=a%3==0
print("Boolean Array={} Type={}".format(ba,type(ba)))
#Step-2: Pass the Boolean Array to the ndarray Object
print("Factors of 3")
print(a[ba])

Random Elements
[53 38 51 26 36 35 51 28 26 35 33 36]
Boolean Array=[False False  True False  True False  True False False False  True  True] Type=<class 'numpy.ndarray'>
Factors of 3
[51 36 51 33 36]


In [19]:
#Create 1D Array with Random 12 Integer Values
from numpy import random as r
a=r.randint(25,55,size=12)
print("Random Elements")
print(a)
#Get All Factors of 5 & 3
#Step-1: Prepare the condition with ndarray Object
ba=(a%3==0) & (a%5==0)
print("Boolean Array={} Type={}".format(ba,type(ba)))
#Step-2: Pass the Boolean Array to the ndarray Object
print("Factors of 5 & 3")
print(a[ba])

Random Elements
[28 40 27 28 49 51 36 45 37 32 43 39]
Boolean Array=[False False False False False False False  True False False False False] Type=<class 'numpy.ndarray'>
Factors of 5 & 3
[45]


In [20]:
#Create 1D Array with Random 15 Integer Values
from numpy import random as r
a=r.randint(25,55,size=15)
print("Random Elements")
print(a)
#Get all Factors of 5 and 3
print("------------------------------------------------")
print("Factors of 5 and 3")
print(a[(a%3==0)&(a%5==0)])

Random Elements
[41 27 27 31 40 31 48 30 39 26 39 25 54 28 36]
------------------------------------------------
Factors of 5 and 3
[30]


In [23]:
#Create 1D Array with Random 15 Integer Values
from numpy import random as r
a=r.randint(25,55,size=15)
print("Random Elements")
print(a)
#Get all Factors of 5 and 3
print("------------------------------------------------")
print("Factors of 5 and 3")
print(a[(a%3==0)&(a%5==0)])

Random Elements
[28 50 33 41 39 50 41 50 45 37 26 30 32 50 54]
------------------------------------------------
Factors of 5 and 3
[45 30]


In [24]:
#Create 1D Array with Random 15 Integer Values
from numpy import random as r
a=r.randint(25,55,size=15)
print("Random Elements")
print(a)
#Get all Factors of 5 and 3
print("------------------------------------------------")
print("Factors of 5 and 3")
print(a[(a%3==0)&(a%5==0)])

Random Elements
[25 40 52 36 44 26 35 42 52 53 30 28 31 27 50]
------------------------------------------------
Factors of 5 and 3
[30]


In [25]:
#Create 1D Array with Random 15 Integer Values
from numpy import random as r
a=r.randint(25,55,size=15)
print("Random Elements")
print(a)
#Get all Factors of 5 and 3
print("------------------------------------------------")
print("Factors of 5 and 3")
print(a[(a%3==0)&(a%5==0)])

Random Elements
[54 28 40 48 31 52 36 40 28 49 43 50 29 30 40]
------------------------------------------------
Factors of 5 and 3
[30]


In [27]:
#Create 1D Array with Random 15 Integer Values
from numpy import random as r
a=r.randint(25,91,size=15)
print("Random Elements")
print(a)
#Get all Factors of 5 and 3
print("------------------------------------------------")
print("Factors of 5 and 3")
print(a[(a%3==0)&(a%5==0)])

Random Elements
[81 50 71 75 64 39 78 71 35 39 62 80 79 52 85]
------------------------------------------------
Factors of 5 and 3
[75]


In [35]:
#Create 1D Array with Random 15 Integer Values
from numpy import random as r
a=r.randint(25,55,size=15)
print("Random Elements")
print(a)
#Get all Factors of 5 and 3
print("------------------------------------------------")
print("Factors of 5 and 3")
print(a[(a%3==0)&(a%5==0)])

Random Elements
[28 44 54 45 30 35 31 49 40 43 40 36 30 36 29]
------------------------------------------------
Factors of 5 and 3
[45 30 30]


In [36]:
#Create 1D Array with Random 15 Integer Values
from numpy import random as r
a=r.randint(25,55,size=15)
print("Random Elements")
print(a)
#Get all Factors of 5 and 3
print("------------------------------------------------")
print("Factors of 5 and 3")
print(a[(a%3==0)&(a%5==0)])

Random Elements
[45 39 43 36 41 48 29 48 54 52 31 30 54 34 29]
------------------------------------------------
Factors of 5 and 3
[45 30]
