In [2]:
#Syntax-1:   numpy.append(1DArray,Value)
#Syntax-2:   numpy.append(1DArray,[Val1,Val2,..,Val-n])

In [3]:
#Create an Object of ndarray
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("ndarray Data")
print(a)

ndarray Data
[10 20 30 40 50 60 70 80 90]


In [4]:
#Append the Data 25 at the end of 1Darray--by using append()
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("ndarray Data")
print(a)
a=np.append(a,25)
print("After append()")
print(a)

ndarray Data
[10 20 30 40 50 60 70 80 90]
After append()
[10 20 30 40 50 60 70 80 90 25]


In [5]:
#Append the Data 35,45,55 at the end of 1Darray--by using append()
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("ndarray Data")
print(a)
a=np.append(a,[35,45,55])
print("After append()")
print(a)

ndarray Data
[10 20 30 40 50 60 70 80 90]
After append()
[10 20 30 40 50 60 70 80 90 35 45 55]


In [8]:
#Create an object of ndarray 
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("Ndarray Data")
print(a,id(a))

Ndarray Data
[10 20 30 40 50 60 70 80 90] 1438783438448


In [9]:
a=np.append(a,[11,22,33])
print("ndarray Data")
print(a,id(a))

ndarray Data
[10 20 30 40 50 60 70 80 90 11 22 33] 1438787986576


In [10]:
#Insert the Values in 1D Array
#Create an object of ndarray 
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("Ndarray Data")
print(a,id(a))

Ndarray Data
[10 20 30 40 50 60 70 80 90] 1438783438256


In [13]:
#Insert the Values 35 at Index 2 in 1D Array
a=np.insert(a,2,35)
print(a)

[10 20 35 30 40 50 60 70 80 90]


In [14]:
#Insert [100,200,300,400] at 4th Index of 1D Array
a=np.insert(a,4,[100,200,300,400])
print(a)

[ 10  20  35  30 100 200 300 400  40  50  60  70  80  90]


In [15]:
#Insert the Values in 1D Array
#Create an object of ndarray 
import numpy as np
a=np.array([10,20,30,40,50,60])
print("Ndarray Data")
print(a,id(a))

Ndarray Data
[10 20 30 40 50 60] 1438783438256


In [16]:
a=np.insert(a,[1,3],[21,41])
print(a)

[10 21 20 30 41 40 50 60]


In [30]:
#Insert a Row in 2DArray
#Create an object of ndarray 
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("2ddarray Data")
print(a)

2ddarray Data
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [31]:
#Insert row [11,22,33] at 1 Row of 2d
a=np.insert(a,1,[11,22,33],axis=0)

In [32]:
print(a)

[[10 20 30]
 [11 22 33]
 [40 50 60]
 [70 80 90]]


In [33]:
#Insert at 1 column [55,65,75,85] of 2d
a=np.insert(a,1,[55,65,75,85],axis=1)

In [34]:
print(a)

[[10 55 20 30]
 [11 65 22 33]
 [40 75 50 60]
 [70 85 80 90]]


In [35]:
#Insert row [10,20,30,40] at Last in 2d
a=np.insert(a,len(a),[10,20,30,40],axis=0)

In [36]:
print(a)

[[10 55 20 30]
 [11 65 22 33]
 [40 75 50 60]
 [70 85 80 90]
 [10 20 30 40]]


In [37]:
#Insert Column [11,21,31,41,51] at Last in Begining
a=np.insert(a,0,[11,21,31,41,51],axis=1)

In [38]:
print(a)

[[11 10 55 20 30]
 [21 11 65 22 33]
 [31 40 75 50 60]
 [41 70 85 80 90]
 [51 10 20 30 40]]


In [39]:
#Update all the 3rd Col Values as [21,22,23,24,25]
a[0:1, 3:4]=21
a[1:2, 3:4]=22
a[2:3, 3:4]=23
a[3:4, 3:4]=24
a[4:5, 3:4]=25

In [41]:
print(a)

[[11 10 55 21 30]
 [21 11 65 22 33]
 [31 40 75 23 60]
 [41 70 85 24 90]
 [51 10 20 25 40]]


In [42]:
#To delete the Element from 1D Array-we use delete()
#Syntax-1:    numpy.delete(1dArray, Index)
#Syntax-2:    numpy.delete(1dArray, [Index1,Index2,...,Index-n] )

In [43]:
#Create an Object of 1D Array
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("Original Array Data")
print(a)
#Delete the value 30 in the ndarray
a=np.delete(a,2)
print("1D Array Data After Delete")
print(a)

Original Array Data
[10 20 30 40 50 60 70 80 90]
1D Array Data After Delete
[10 20 40 50 60 70 80 90]


In [44]:
#Create an Object of 1D Array 
import numpy as np
a=np.array([10,20,30,50,60,70,80,90])
print("Original 1D Array Data")
print(a) # [10 20 30 50 60 70 80 90]
#Delete  30 , 70 and 80 from 1D
a=np.delete(a,[2,-3,-2])
print("1D Array Data after delete")
print(a)

Original 1D Array Data
[10 20 30 50 60 70 80 90]
1D Array Data after delete
[10 20 50 60 90]


In [45]:
#Create an Object of 2D Array
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Original 2D Array Data")
print(a)
#Delete 1 Row from 2D
a=np.delete(a,1,axis=0)
print("2D Array Data After Row Deletion")
print(a)

Original 2D Array Data
[[10 20 30]
 [40 50 60]
 [70 80 90]]
2D Array Data After Row Deletion
[[10 20 30]
 [70 80 90]]


In [46]:
#Create an Object of 2D Array
import numpy as np
a=np.arange(5*5).reshape(5,5)
print("Original 2D Array Data")
print(a)
#Delete 1 Row, 2row and last row  from 2D 
a=np.delete(a,[1,2,-1],axis=0)
print("2D Array Data After Row Deletion")
print(a)

Original 2D Array Data
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
2D Array Data After Row Deletion
[[ 0  1  2  3  4]
 [15 16 17 18 19]]


In [47]:
#Create an Object of 2D Array
import numpy as np
a=np.arange(5*5).reshape(5,5)
print("Original 2D Array Data")
print(a)
#Delete 1 Column from 2D
a=np.delete(a,1,axis=1)
print("2D Array Data After Column Deletion")
print(a)

Original 2D Array Data
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
2D Array Data After Column Deletion
[[ 0  2  3  4]
 [ 5  7  8  9]
 [10 12 13 14]
 [15 17 18 19]
 [20 22 23 24]]


In [49]:
#Create an Object of 2D Array
import numpy as np
a=np.arange(5*5).reshape(5,5)
print("Original Array Data")
print(a)
#Delete 0th,last Two Columns from 2D 
a=np.delete(a,[0,-2,-1],axis=1)
print("2D Array Data After Columns Deletion")
print(a)

Original Array Data
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
2D Array Data After Columns Deletion
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]
