In [1]:
#dot()---------------> Calculates Dot Product of Two Arrays
#Syntax: varname=numpy.dot(ndarray1,ndarray2)

In [3]:
#Create an Object of 1d Arrays
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print("First 1d Array Data=",a)
print("Second 1d Array Data=",b)
c=np.dot(a,b)
print("Dot Product of 1D Arrays={}".format(c))

First 1d Array Data= [1 2 3]
Second 1d Array Data= [4 5 6]
Dot Product of 1D Arrays=32


In [4]:
#Create an Object of 2d Arrays
import numpy as np
a=np.array([1,3,5,2]).reshape(2,2)
b=np.array([2,4,6,3]).reshape(2,2)
print("First 2d Array\n",a)
print("Second 2d Array\n",b)
c=np.dot(a,b)
print("Dot Product of 2D Arrays\n",c)

First 2d Array
 [[1 3]
 [5 2]]
Second 2d Array
 [[2 4]
 [6 3]]
Dot Product of 2D Arrays
 [[20 13]
 [22 26]]


In [5]:
#Create an Object of 2d Arrays
import numpy as np
a=np.array([1,2,3,4,6,7]).reshape(3,2)
b=np.array([4,5,6,7]).reshape(2,2)
print("First 2d Array\n",a)
print("Second 2d Array\n",b)
c=np.dot(a,b)
print("Dot Product of 2D Arrays\n",c)

First 2d Array
 [[1 2]
 [3 4]
 [6 7]]
Second 2d Array
 [[4 5]
 [6 7]]
Dot Product of 2D Arrays
 [[16 19]
 [36 43]
 [66 79]]


In [6]:
# inner()------------> Calculates Inner Product of Two Arrays
#Syntax:  varname=numpy.inner(ndarray1,ndarray2) 

In [7]:
#Create an Object of 1d Arrays---inner()
import numpy as np
a=np.array([1,3,5])
b=np.array([2,4,6])
print("First 2d Array=",a)
print("Second 2d Array=",b)
c=np.inner(a,b)
print("Inner Product of 1d Arrays=",c)

First 2d Array= [1 3 5]
Second 2d Array= [2 4 6]
Inner Product of 1d Arrays= 44


In [8]:
#inner Product of 2D Arrays
import numpy as np
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([4,5,6,7]).reshape(2,2)
print("First 2d Array\n",a)
print("Second 2d Array\n",b)
c=np.inner(a,b)
print("Inner Product of 2d Arrays\n",c)

First 2d Array
 [[1 2]
 [3 4]]
Second 2d Array
 [[4 5]
 [6 7]]
Inner Product of 2d Arrays
 [[14 20]
 [32 46]]


In [9]:
#Note:  dot() of 1dArray is equal to inner() of 1dArray()
#But they are different in the 2-d.

In [10]:
# outer()------------> Calculates Outer  Product of Two Arrays
#Syntax:  varname=numpy.outer(ndarray1,ndarray2)

In [12]:
#Create an Object of 1d Arrays----outer()
import numpy as np
a=np.array([1,3,5])
b=np.array([2,4,6])
print("First 1d Array=",a)
print("Second 1d Array=",b)
c=np.outer(a,b)
print("Outer Product of 2d Arrays\n",c)

First 1d Array= [1 3 5]
Second 1d Array= [2 4 6]
Outer Product of 2d Arrays
 [[ 2  4  6]
 [ 6 12 18]
 [10 20 30]]


In [13]:
#Create an Object of 1d Arrays----outer()
a=np.array([1,3,5,7]).reshape(2,2)
b=np.array([2,4,6,8]).reshape(2,2)
print("2-D Array a\n{}".format(a))
print("2-D Array b\n{}".format(b))
c=np.outer(a,b)
print("Outer Product of 2-D Arrays\n{}".format(c))

2-D Array a
[[1 3]
 [5 7]]
2-D Array b
[[2 4]
 [6 8]]
Outer Product of 2-D Arrays
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


In [14]:
#It is Present in "linalg" module 
# det()---------------> Calculates Determinant of Matrix (2dArray)
#Syntax:   varname=numpy.linalg.det(ndarray) here ndarray must be square matrix
#Formula for det= (a*d)-(b*c)

In [15]:
#Creating an Object of 2D Array
import numpy as np
a=np.array([10,2,4,3]).reshape(2,2)
print("2d Array a\n",a)
b=np.linalg.det(a)
print("Det of 2D Matrix=",np.around(b,1))

2d Array a
 [[10  2]
 [ 4  3]]
Det of 2D Matrix= 22.0


In [16]:
a=np.array([10,2,4,3,3,4]).reshape(2,3)
print("-"*50)
print("2-D Array a\n{}".format(a))
d=np.linalg.det(a) # LinAlgError: Last 2 dimensions of the array must be square
print("det of 2-D Matrix=",np.round(d,2))

--------------------------------------------------
2-D Array a
[[10  2  4]
 [ 3  3  4]]


LinAlgError: Last 2 dimensions of the array must be square

In [17]:
import numpy as np
a=np.array([10,2,4,3,3,4,1,6,4]).reshape(3,3)
print("-"*50)
print("2-D Array a\n{}".format(a))
d=np.linalg.det(a)
print("det of 2-D Matrix=",np.round(d,2))

--------------------------------------------------
2-D Array a
[[10  2  4]
 [ 3  3  4]
 [ 1  6  4]]
det of 2-D Matrix= -76.0


In [19]:
# solve()------------->Solves the Linear Equations in the form of Matrix format
#Syntax:  varname=numpy.linalg.solve(ndarray1,ndarray2)

In [20]:
#Problem:   Solve the following Sysmtem Linear Equations
#          2x+4y=5
#          6x+8y=6    Find the values of x and y

In [2]:
import numpy as np
#Create ndarray for x and y coff
a=np.array([[2,4],[6,8]])
b=np.array([5,6])
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
sol=np.linalg.solve(a,b)
print("Value of x=",np.around(sol[0],1))
print("Value of y=",np.around(sol[1],1))

Matrix-A
[[2 4]
 [6 8]]
Matrix-B
[5 6]
Value of x= -2.0
Value of y= 2.2


In [3]:
#Problem:   Solve the following Sysmtem Linear Equations
# 4x+2y=8
# 5x+3y=9    Find the values of x and y

In [6]:
import numpy as np
a=np.array([4,2,5,3]).reshape(2,2)
b=np.array([8,9])
sol=np.linalg.solve(a,b)
print("Value of x=",np.around(sol[0],1))
print("Value of y=",np.around(sol[1],1))

Value of x= 3.0
Value of y= -2.0


In [7]:
#Problem: Solve the following Sysmtem Linear Equations
# x+2y-z=4
# 3x-y+z=5
# 2x+3y+2z=7

In [8]:
import numpy as np
a=np.array([[1,2,-1],[3,-1,1],[2,3,2]])
b=np.array([4,5,7])
sol=np.linalg.solve(a,b)
print("Values of x=",np.around(sol[0],2))
print("Values of y=",np.around(sol[1],2))
print("Values of z=",np.around(sol[2],2))

Values of x= 2.0
Values of y= 1.0
Values of z= 0.0


In [10]:
# inv()----->Calculates of Inverse of a Martix (2D Array)
#Syntax: varname=numpy.linalg.inv(ndarrayobject)

In [1]:
import numpy as np
a=np.array([4,2,5,3]).reshape(2,2)
print(a)
b=np.linalg.inv(a)
print("Inverse of Given Matrix")
print(b)

[[4 2]
 [5 3]]
Inverse of Given Matrix
[[ 1.5 -1. ]
 [-2.5  2. ]]


In [2]:
import numpy as np
a=np.array([[1,2,-1],[3,-1,1],[2,3,2]])
print("Given Matrix")
print(a)
b=np.linalg.inv(a)
print("Inverse of Given Matrix")
for row in b:
    for val in row:
        print("{}".format(np.round(val,2)),end="  ")
    print()

Given Matrix
[[ 1  2 -1]
 [ 3 -1  1]
 [ 2  3  2]]
Inverse of Given Matrix
0.21  0.29  -0.04  
0.17  -0.17  0.17  
-0.46  -0.04  0.29  


In [3]:
import numpy as np
a=np.array([4,2,5,3]).reshape(2,2)
print("Given Matrix")
print(a)
b=np.trace(a)
print("Trace Given Matrix=",b)

Given Matrix
[[4 2]
 [5 3]]
Trace Given Matrix= 7


In [5]:
import numpy as np
a=np.array([[1,2,-1],[3,-1,1],[2,3,2]])
print("Given Matrix")
print(a)
b=np.trace(a)
print("Trace Given Matrix=",b)

Given Matrix
[[ 1  2 -1]
 [ 3 -1  1]
 [ 2  3  2]]
Trace Given Matrix= 2


In [6]:
import numpy as np
a=np.random.randint(10,20,size=(3,3))
print("Given Matrix")
print(a)
b=np.trace(a)
print("Trace Given Matrix=",b)

Given Matrix
[[14 10 19]
 [17 17 16]
 [14 13 16]]
Trace Given Matrix= 47


In [7]:
# Problem: x+y=2
# x+y=4  for Det of any matrix is 0 then there is no solution.
a=np.array([1,1,1,1]).reshape(2,2)
b=np.array([2,4])
sol=np.linalg.solve(a,b)
print("Val of x=",np.round(sol[0],2))
print("Val of y=",np.round(sol[1],2))

LinAlgError: Singular matrix