In [1]:
#Numpy--Slicing Operations on 1-D
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("Content of ndarray a={}".format(a))
print("Dimension of ndarray={}".format(a.ndim))
print("Shape of ndarray={}".format(a.shape))

Content of ndarray a=[10 20 30 40 50 60 70 80 90]
Dimension of ndarray=1
Shape of ndarray=(9,)


In [2]:
#Get 10 20 30 40  from 1D Array
b=a[0:4]
print(b,type(b))

[10 20 30 40] <class 'numpy.ndarray'>


In [3]:
print(a)

[10 20 30 40 50 60 70 80 90]


In [4]:
#Get the Elements 60 70 80 90
print(a[5:9])

[60 70 80 90]


In [5]:
#Get the Elements 60 70 80 90-----Another Way
print(a[5:])

[60 70 80 90]


In [7]:
#Get the Elements 30,40,50,60 with -VE Slicing
print(a[-7:-3])

[30 40 50 60]


In [8]:
print(a)

[10 20 30 40 50 60 70 80 90]


In [9]:
#Get 10 30 50 70 70 
print(a[::2])

[10 30 50 70 90]


In [10]:
#Get 20 40 60 80 
print(a[1::2])

[20 40 60 80]


In [11]:
print(a)

[10 20 30 40 50 60 70 80 90]


In [12]:
#Get 10 40 70 
print(a[::3])

[10 40 70]


In [13]:
#Get 90,80,70,60 in Backward Direction 
print(a[-1:-5:-1])

[90 80 70 60]


In [14]:
#Get 90 70 50 30  10 in Backward Direction with -VE Step
print(a[::-2])

[90 70 50 30 10]


In [16]:
#Get 90 70 50 30  10 in Backward Direction with +VE Step
print(a[::2][::-1])

[90 70 50 30 10]


In [1]:
#Numpy-Slicing Operations on 2-d
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,34,1,11,13,14,15,16]).reshape(4,4)
print("Content of ndarray\n{}".format(a))
print("Dimension of ndarray={}".format(a.ndim))
print("Shape of ndarray={}".format(a.shape))

Content of ndarray
[[10 20 30 40]
 [50 60 70 80]
 [90 34  1 11]
 [13 14 15 16]]
Dimension of ndarray=2
Shape of ndarray=(4, 4)


In [6]:
#Get [60,70,80] from 2D Array
a[1:2,1:4]

array([[60, 70, 80]])

In [7]:
#Get [60,70,80] from 2D Array---Another Way
a[1:2,1:]

array([[60, 70, 80]])

In [8]:
#Get [60,70,80] from 2D Array with -ve Indices
a[-3:-2,-3:]

array([[60, 70, 80]])

In [10]:
#Get 60,70,34,1 from 2D Array
a[1:3,1:3]

array([[60, 70],
       [34,  1]])

In [12]:
#Get 60,70,34,1 from 2D Array---Another Way
a[1:3:1,1:3:1]

array([[60, 70],
       [34,  1]])

In [13]:
#Get 60,70,34,1 from 2D Array---Another Way
a[1:3:,1:3:]

array([[60, 70],
       [34,  1]])

In [14]:
print(a)

[[10 20 30 40]
 [50 60 70 80]
 [90 34  1 11]
 [13 14 15 16]]


In [15]:
print(a[1:,1:4])

[[60 70 80]
 [34  1 11]
 [14 15 16]]


In [16]:
print(a[1:,1:3])

[[60 70]
 [34  1]
 [14 15]]


In [17]:
a[1::,1:3:1]

array([[60, 70],
       [34,  1],
       [14, 15]])

In [18]:
a[1::1,1:3:1]

array([[60, 70],
       [34,  1],
       [14, 15]])

In [19]:
print(a)

[[10 20 30 40]
 [50 60 70 80]
 [90 34  1 11]
 [13 14 15 16]]


In [20]:
a[::2,::2]

array([[10, 30],
       [90,  1]])

In [21]:
#Get First Column and Last Column
a[::,::3]

array([[10, 40],
       [50, 80],
       [90, 11],
       [13, 16]])

In [22]:
a[::1,0::3]

array([[10, 40],
       [50, 80],
       [90, 11],
       [13, 16]])

In [23]:
#Get 50,60,70,80,13,14,15,16
a[1::2,:]

array([[50, 60, 70, 80],
       [13, 14, 15, 16]])

In [24]:
a[1::2,::]

array([[50, 60, 70, 80],
       [13, 14, 15, 16]])

In [25]:
a[1::2,0::1]

array([[50, 60, 70, 80],
       [13, 14, 15, 16]])

In [4]:
#Create 3D Array with Random Integer Values with shape(3,3,3)
import numpy.random as r
a=r.randint(10,20,(3,3,3))
print("3-d Array")
print(a)
print("Shape of a={}".format(a.shape))
print("Dimension of a={}".format(a.ndim))

3-d Array
[[[11 19 16]
  [11 17 11]
  [14 10 16]]

 [[19 19 14]
  [13 15 18]
  [16 13 16]]

 [[15 10 17]
  [10 14 13]
  [10 11 15]]]
Shape of a=(3, 3, 3)
Dimension of a=3


In [2]:
#Get First Two Matrices from 3D
print(a[0:2])

[[[13 18 14]
  [16 10 11]
  [11 18 16]]

 [[19 11 15]
  [19 16 12]
  [10 11 18]]]


In [3]:
#Get First and Last Matrix
print(a[0::2])

[[[13 18 14]
  [16 10 11]
  [11 18 16]]

 [[17 17 11]
  [16 17 13]
  [14 18 12]]]


In [6]:
print(a)

[[[11 19 16]
  [11 17 11]
  [14 10 16]]

 [[19 19 14]
  [13 15 18]
  [16 13 16]]

 [[15 10 17]
  [10 14 13]
  [10 11 15]]]


In [7]:
#Get All 0th row of all Columns of all Matrices
print(a[:,0:1,0:3])

[[[11 19 16]]

 [[19 19 14]]

 [[15 10 17]]]


In [8]:
#Get All 0th Col of all Rows of all Matrices
print(a[:,:,0:1])

[[[11]
  [11]
  [14]]

 [[19]
  [13]
  [16]]

 [[15]
  [10]
  [10]]]


In [9]:
print(a)

[[[11 19 16]
  [11 17 11]
  [14 10 16]]

 [[19 19 14]
  [13 15 18]
  [16 13 16]]

 [[15 10 17]
  [10 14 13]
  [10 11 15]]]


In [10]:
#Get First and Last Matrices 1st Row Elements of Corresposnding Matrices
print(a[::2,1:2,::])

[[[11 17 11]]

 [[10 14 13]]]


In [12]:
print(a[::2,2::,1::])

[[[10 16]]

 [[11 15]]]


In [13]:
print(a[::2,:2:2,2::2])

[[[16]]

 [[17]]]


In [14]:
print(a[2::,2::,::2])

[[[10 15]]]
