In [2]:
#trunc()
#Create an Object of 1darray
import numpy as np
a=np.array([-3.1666, 3.6667,2.999,1.999,3.999,5.6666])
print("Original Array Data=",a)
b=np.trunc(a)
print("Truncated ndarray Object=",b)

Original Array Data= [-3.1666  3.6667  2.999   1.999   3.999   5.6666]
Truncated ndarray Object= [-3.  3.  2.  1.  3.  5.]


In [4]:
#Create an Object of 2darray
import numpy as np
a=np.array([-3.1666, 3.6667,2.999,1.999,3.999,5.6666]).reshape(3,2)
print("Original Array Data\n",a)
b=np.trunc(a)
print("Truncated ndarray Object\n",b)

Original Array Data
 [[-3.1666  3.6667]
 [ 2.999   1.999 ]
 [ 3.999   5.6666]]
Truncated ndarray Object
 [[-3.  3.]
 [ 2.  1.]
 [ 3.  5.]]


In [6]:
#fix()
#Create an Object of 1darray
import numpy as np
a=np.array([-3.1666, 3.6667,2.999,1.999,3.999,5.6666]).reshape(3,2)
print("Original Array Data\n",a)
b=np.fix(a)
print("Truncated ndarray Object\n",b)

Original Array Data
 [[-3.1666  3.6667]
 [ 2.999   1.999 ]
 [ 3.999   5.6666]]
Truncated ndarray Object
 [[-3.  3.]
 [ 2.  1.]
 [ 3.  5.]]


In [9]:
#Rounding the Decimals By Using around()
import numpy as np
arr=np.around(3.1666,2)
print(arr)

3.17


In [10]:
#Create an Object of 1darray
import numpy as np
a=np.array([-3.1666, 3.6667,2.995,1.999,3.919,5.6646])
print("Original Array Data\n",a)
b=np.around(a,2)
print("Rounded Array Values\n",b)

Original Array Data
 [-3.1666  3.6667  2.995   1.999   3.919   5.6646]
Rounded Array Values
 [-3.17  3.67  3.    2.    3.92  5.66]


In [11]:
#Create an Object of 2d Array
import numpy as np
a=np.array([-3.1666, 3.6667,2.995,1.999,3.919,5.6646]).reshape(3,2)
print("Original Array Data\n",a)
b=np.around(a,2)
print("Rounded Array Values\n",b)

Original Array Data
 [[-3.1666  3.6667]
 [ 2.995   1.999 ]
 [ 3.919   5.6646]]
Rounded Array Values
 [[-3.17  3.67]
 [ 3.    2.  ]
 [ 3.92  5.66]]


In [12]:
#Floor the Elements of Array---floor()
import numpy as np
a=np.floor([-3.1666, 3.6667])
print(a)

[-4.  3.]


In [13]:
#Create an Object of 1darray----floor()
import numpy as np
a=np.array([-3.1666, 3.6667,2.995,1.999,3.919,-5.6646])
print("Original Array Data\n",a)
b=np.floor(a)
print("Floor Array Values\n",b)

Original Array Data
 [-3.1666  3.6667  2.995   1.999   3.919  -5.6646]
Floor Array Values
 [-4.  3.  2.  1.  3. -6.]


In [14]:
#The ceil() function rounds-off decimal to nearest Highest OR  upper integer.

In [15]:
#Create an Object of 1darray
import numpy as np
a=np.ceil([-3.1666, 3.6667])
print(a)

[-3.  4.]


In [16]:
#Create an Object of 1darray
import numpy as np
a=np.array([-3.1666, 3.6667,2.995,1.999,3.00001,-5.6646])
print("Original Array Data\n",a)
b=np.ceil(a)
print("Ceil Array Values\n",b)

Original Array Data
 [-3.1666   3.6667   2.995    1.999    3.00001 -5.6646 ]
Ceil Array Values
 [-3.  4.  3.  2.  4. -5.]


In [17]:
#Create an Object of 2darray
import numpy as np
a=np.array([-3.1666, 3.6667,2.995,1.999,3.00001,-5.6646]).reshape(3,2)
print("Original Array Data\n",a)
b=np.ceil(a)
print("Ceil Array Values\n",b)

Original Array Data
 [[-3.1666   3.6667 ]
 [ 2.995    1.999  ]
 [ 3.00001 -5.6646 ]]
Ceil Array Values
 [[-3.  4.]
 [ 3.  2.]
 [ 4. -5.]]
