In [1]:
#Sort the 1-d Array
import numpy as np
a=np.random.randint(100,234,size=8)
print("1-d Random Data--Original")
print(a)
#Sort the Random Data
a=np.sort(a)
print("1-d Sorted Data in Ascending Order")
print(a)

1-d Random Data--Original
[186 153 183 143 134 185 231 129]
1-d Sorted Data in Ascending Order
[129 134 143 153 183 185 186 231]


In [3]:
#Sort the 1-d Array Data in Descending Order
import numpy as np
a=np.random.randint(100,234,size=8)
print("1-d Random Data--Original")
print(a)
#Sort the Random Data
a=np.sort(a)
print("1-d Sorted Data in Descending Order")
print(a[::-1])

1-d Random Data--Original
[164 126 170 168 232 191 172 137]
1-d Sorted Data in Descending Order
[232 191 172 170 168 164 137 126]


In [4]:
#Sort the 2D Array Data
import numpy as np
a=np.array([15,10,25,11,12,18,29,31,13]).reshape(3,3)
print("2D Random Data--Original")
print(a)

2D Random Data--Original
[[15 10 25]
 [11 12 18]
 [29 31 13]]


In [5]:
#Sort the 2D Array Data
import numpy as np
a=np.array([15,10,25,11,12,18,29,31,13]).reshape(3,3)
print("2D Random Data--Original")
print(a)
#Sort the 2D Array Data
a=np.sort(a)
print("2D Random Data--Sorted")
print(a)

2D Random Data--Original
[[15 10 25]
 [11 12 18]
 [29 31 13]]
2D Random Data--Sorted
[[10 15 25]
 [11 12 18]
 [13 29 31]]


In [7]:
#Sort the 2D Array Data
import numpy as np
a=np.array([15,10,25,11,12,18,29,31,13]).reshape(3,3)
print("2D Random Data--Original")
print(a)
#Sort the 2D Array Data
a=np.sort(a,axis=1)   # Here axis=1 Represents Rows (Default axis=1 -->Rows)
print("2D Random Data--Sorted")
print(a)

2D Random Data--Original
[[15 10 25]
 [11 12 18]
 [29 31 13]]
2D Random Data--Sorted
[[10 15 25]
 [11 12 18]
 [13 29 31]]


In [8]:
#Sort the 2D Array Data
import numpy as np
a=np.array([15,10,25,11,12,18,29,31,13]).reshape(3,3)
print("2D Random Data--Original")
print(a)
#Sort the 2D Array Data
a=np.sort(a,axis=0)  #Here axis=0 Represents Columns
print("2D Random Data--Sorted")
print(a)

2D Random Data--Original
[[15 10 25]
 [11 12 18]
 [29 31 13]]
2D Random Data--Sorted
[[11 10 13]
 [15 12 18]
 [29 31 25]]


In [2]:
#program for Sorting Programmer-Defined Tuples of List Data--Customized Data
import numpy as np
dt=[("name","U7"),("age",int),("height",int)]
lst=[("Ramesh",35,175),("Rajesh",40,165),("Rakesh",34,171),
     ("Rossum",60,162),("Raju",35,174),("Ranjeet",40,169),("Ramesh",35,175)]
a=np.array(lst,dtype=dt)
print("Original Data")
for record in a:
    print(record)
a=np.sort(a,order="name")
print("Sorted Data Based on Name--Ascending Order")
for record in a:
    print(record)

Original Data
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Rakesh', 34, 171)
('Rossum', 60, 162)
('Raju', 35, 174)
('Ranjeet', 40, 169)
('Ramesh', 35, 175)
Sorted Data Based on Name--Ascending Order
('Rajesh', 40, 165)
('Raju', 35, 174)
('Rakesh', 34, 171)
('Ramesh', 35, 175)
('Ramesh', 35, 175)
('Ranjeet', 40, 169)
('Rossum', 60, 162)


In [4]:
#program for Sorting Programmer-Defined Tuples of List Data--Customized Data
import numpy as np
dt=[("name","U7"),("age",int),("height",int)]
lst=[("Ramesh",35,175),("Rajesh",40,165),("Rakesh",34,171),
     ("Rossum",60,162),("Raju",35,174),("Ranjeet",40,169),("Ramesh",35,175)]
a=np.array(lst,dtype=dt)
print("Original Data")
for record in a:
    print(record)
a=np.sort(a,order="name")[::-1]
print("Sorted Data Based on Name--Descending Order")
for record in a:
    print(record)

Original Data
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Rakesh', 34, 171)
('Rossum', 60, 162)
('Raju', 35, 174)
('Ranjeet', 40, 169)
('Ramesh', 35, 175)
Sorted Data Based on Name--Descending Order
('Rossum', 60, 162)
('Ranjeet', 40, 169)
('Ramesh', 35, 175)
('Ramesh', 35, 175)
('Rakesh', 34, 171)
('Raju', 35, 174)
('Rajesh', 40, 165)


In [5]:
#program for Sorting Programmer-Defined Tuples of List Data--Customized Data
import numpy as np
dt=[("name","U7"),("age",int),("height",int)]
lst=[("Ramesh",35,175),("Rajesh",40,165),("Rakesh",34,171),
     ("Rossum",60,162),("Raju",35,174),("Ranjeet",40,169),("Ramesh",35,175)]
a=np.array(lst,dtype=dt)
print("Original Data")
for record in a:
    print(record)
a=np.sort(a,order="height")
print("Sorted Data Based on Height--Ascending Order")
for record in a:
    print(record)

Original Data
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Rakesh', 34, 171)
('Rossum', 60, 162)
('Raju', 35, 174)
('Ranjeet', 40, 169)
('Ramesh', 35, 175)
Sorted Data Based on Height
('Rossum', 60, 162)
('Rajesh', 40, 165)
('Ranjeet', 40, 169)
('Rakesh', 34, 171)
('Raju', 35, 174)
('Ramesh', 35, 175)
('Ramesh', 35, 175)


In [7]:
#program for Sorting Programmer-Defined Tuples of List Data--Customized Data
import numpy as np
dt=[("name","U7"),("age",int),("height",int)]
lst=[("Ramesh",35,175),("Rajesh",40,165),("Rakesh",34,171),
     ("Rossum",60,162),("Raju",35,174),("Ranjeet",40,169),("Ramesh",35,175)]
a=np.array(lst,dtype=dt)
print("Original Data")
for record in a:
    print(record)
a=np.sort(a,order=("age","height"))
print("Sorted Data Based on Age and Height--Ascending Order")
for record in a:
    print(record)

Original Data
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Rakesh', 34, 171)
('Rossum', 60, 162)
('Raju', 35, 174)
('Ranjeet', 40, 169)
('Ramesh', 35, 175)
Sorted Data Based on Age and Height--Ascending Order
('Rakesh', 34, 171)
('Raju', 35, 174)
('Ramesh', 35, 175)
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Ranjeet', 40, 169)
('Rossum', 60, 162)


In [8]:
#program for Sorting Programmer-Defined Tuples of List Data--Customized Data---heap sort
import numpy as np
dt=[("name","U7"),("age",int),("height",int)]
lst=[("Ramesh",35,175),("Rajesh",40,165),("Rakesh",34,171),
     ("Rossum",60,162),("Raju",35,174),("Ranjeet",40,169),("Ramesh",35,175)]
a=np.array(lst,dtype=dt)
print("Original Data")
for record in a:
    print(record)
a=np.sort(a,order=("age","height"),kind="heapsort")
print("Sorted Data Based on Age and Height--Ascending Order")
for record in a:
    print(record)

Original Data
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Rakesh', 34, 171)
('Rossum', 60, 162)
('Raju', 35, 174)
('Ranjeet', 40, 169)
('Ramesh', 35, 175)
Sorted Data Based on Age and Height--Ascending Order
('Rakesh', 34, 171)
('Raju', 35, 174)
('Ramesh', 35, 175)
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Ranjeet', 40, 169)
('Rossum', 60, 162)


In [10]:
#program for Sorting Programmer-Defined Tuples of List Data--Customized Data
import numpy as np
dt=[("name","U7"),("age",int),("height",int)]
lst=[("Ramesh",35,175),("Rajesh",40,165),("Rakesh",34,171),
     ("Rossum",60,162),("Raju",35,174),("Ranjeet",40,169),("Ramesh",35,175)]
a=np.array(lst,dtype=dt)
print("Original Data")
for record in a:
    print(record)
a=np.sort(a,order=("age","height"),kind="quicksort")
print("Sorted Data Based on Age and Height--Ascending Order")
for record in a:
    print(record)

Original Data
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Rakesh', 34, 171)
('Rossum', 60, 162)
('Raju', 35, 174)
('Ranjeet', 40, 169)
('Ramesh', 35, 175)
Sorted Data Based on Age and Height--Ascending Order
('Rakesh', 34, 171)
('Raju', 35, 174)
('Ramesh', 35, 175)
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Ranjeet', 40, 169)
('Rossum', 60, 162)


In [11]:
#program for Sorting Programmer-Defined Tuples of List Data--Customized Data
import numpy as np
dt=[("name","U7"),("age",int),("height",int)]
lst=[("Ramesh",35,175),("Rajesh",40,165),("Rakesh",34,171),
     ("Rossum",60,162),("Raju",35,174),("Ranjeet",40,169),("Ramesh",35,175)]
a=np.array(lst,dtype=dt)
print("Original Data")
for record in a:
    print(record)
a=np.sort(a,order=("age","height"),kind="mergesort")
print("Sorted Data Based on Age and Height--Asceding Order")
for record in a:
    print(record)

Original Data
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Rakesh', 34, 171)
('Rossum', 60, 162)
('Raju', 35, 174)
('Ranjeet', 40, 169)
('Ramesh', 35, 175)
Sorted Data Based on Age and Height--Asceding Order
('Rakesh', 34, 171)
('Raju', 35, 174)
('Ramesh', 35, 175)
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Ranjeet', 40, 169)
('Rossum', 60, 162)


In [12]:
#program for Sorting Programmer-Defined Tuples of List Data--Customized Data
import numpy as np
dt=[("name","U7"),("age",int),("height",int)]
lst=[("Ramesh",35,175),("Rajesh",40,165),("Rakesh",34,171),
     ("Rossum",60,162),("Raju",35,174),("Ranjeet",40,169),("Ramesh",35,175)]
a=np.array(lst,dtype=dt)
print("Original Data")
for record in a:
    print(record)
a=np.sort(a,order=("age","height"),kind="bubblesort")
print("Sorted Data Based on Age and Height--Ascending Order")
for record in a:
    print(record)

Original Data
('Ramesh', 35, 175)
('Rajesh', 40, 165)
('Rakesh', 34, 171)
('Rossum', 60, 162)
('Raju', 35, 174)
('Ranjeet', 40, 169)
('Ramesh', 35, 175)


ValueError: sort kind must be one of 'quick', 'heap', or 'stable' (got 'bubblesort')