In [1]:
#sum()
#Create an Object of 1d Array
import numpy as np
a=np.array([1,2,3])
b=np.sum(a)
print("Original Array Data")
print(a)
print("Sum=",b)

Original Array Data
[1 2 3]
Sum= 6


In [2]:
#Create an Object of 1d Arrays
import numpy as np
a=np.array([1,2,3])
b=np.array([1,2,3])
c=np.sum([a,b])
print("Original 1d Array-1")
print(a)
print("Original 1d Array-2")
print(b)
print("Sum=",c)

Original 1d Array-1
[1 2 3]
Original 1d Array-2
[1 2 3]
Sum= 12


In [3]:
#Create an Object of 1d Arrays----Column-wise
import numpy as np
a=np.array([1,2,3])
b=np.array([1,2,3])
c=np.sum([a,b],axis=0)  #Column
print("original 1d Array-1")
print(a)
print("Original 1d Array-2")
print(b)
print("Sum=",c)

original 1d Array-1
[1 2 3]
Original 1d Array-2
[1 2 3]
Sum= [2 4 6]


In [5]:
#Create an Object of 1d Arrays----Row-wise
import numpy as np
a=np.array([1,2,3])
b=np.array([1,2,3])
c=np.sum([a,b],axis=1)  #Row
print("original 1d Array-1")
print(a)
print("Original 1d Array-2")
print(b)
print("Sum=",c)

original 1d Array-1
[1 2 3]
Original 1d Array-2
[1 2 3]
Sum= [6 6]


In [6]:
#Create an Object of 2d Array
import numpy as np
a=np.array([10,20,30,40,50,60]).reshape(2,3)
print("2D Array Data")
print(a)
b=np.sum(a)
print("Sum=",b)

2D Array Data
[[10 20 30]
 [40 50 60]]
Sum= 210


In [7]:
#Create an Object of 2d Array----Column-wise
import numpy as np
a=np.array([10,20,30,40,50,60]).reshape(2,3)
print("2D Array Data")
print(a)
b=np.sum(a,axis=0)
print("Sum=",b)

2D Array Data
[[10 20 30]
 [40 50 60]]
Sum= [50 70 90]


In [8]:
#Create an Object of 2d Array----Row-wise
import numpy as np
a=np.array([10,20,30,40,50,60]).reshape(2,3)
print("2D Array Data")
print(a)
b=np.sum(a,axis=1)
print("Sum=",b)

2D Array Data
[[10 20 30]
 [40 50 60]]
Sum= [ 60 150]


In [9]:
#Create an Object of 2d Arrays----Column-wise
import numpy as np
a=np.array([10,20,30,40,50,60]).reshape(2,3)
b=np.array([1,2,3,4,5,6]).reshape(2,3)
print("2D Array-1")
print(a)
print("2D Array-2")
print(b)
c=np.sum([a,b],axis=0)
print("Sum=",c)

2D Array-1
[[10 20 30]
 [40 50 60]]
2D Array-2
[[1 2 3]
 [4 5 6]]
Sum= [[11 22 33]
 [44 55 66]]


In [10]:
#cumsum()
#Create an Object of 1d Array
import numpy as np
a=np.array([1,2,3,4])
b=np.cumsum(a)
print("Original Array Data")
print(a)
print("Cummulative Sum=",b)

Original Array Data
[1 2 3 4]
Cummulative Sum= [ 1  3  6 10]


In [12]:
#Create an Object of 1d Arrays---Column-wise
import numpy as np
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
c=np.cumsum([a,b],axis=0)
print("Original 1d Array-1")
print(a)
print("original 1d Array-2")
print(b)
print("Cummulative Sum")
print(c)

Original 1d Array-1
[1 2 3 4]
original 1d Array-2
[1 2 3 4]
Cummulative Sum
[[1 2 3 4]
 [2 4 6 8]]


In [14]:
#Create an Object of 1d Arrays----Row-wise
import numpy as np
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
c=np.cumsum([a,b],axis=1)
print("Original 1d Array-1")
print(a)
print("Original 1d Array-2")
print(b)
print("Cummulative Sum")
print(c)

Original 1d Array-1
[1 2 3 4]
Original 1d Array-2
[1 2 3 4]
Cummulative Sum
[[ 1  3  6 10]
 [ 1  3  6 10]]


In [15]:
#Create an Object of 2d Array-----Column-wise
import numpy as np
a=np.array([10,20,30,40,50,60]).reshape(2,3)
print("2D Array Data")
print(a)
b=np.cumsum(a,axis=0)
print("Cummulative Sum")
print(b)

2D Array Data
[[10 20 30]
 [40 50 60]]
Cummulative Sum
[[10 20 30]
 [50 70 90]]


In [16]:
#Create an Object of 2d Array-----Row-wise
import numpy as np
a=np.array([10,20,30,40,50,60]).reshape(2,3)
print("2d Array Data")
print(a)
b=np.cumsum(a,axis=1)
print("Cummulative Sum")
print(b)

2d Array Data
[[10 20 30]
 [40 50 60]]
Cummulative Sum
[[ 10  30  60]
 [ 40  90 150]]


In [17]:
#Create an Object of 2d Arrays----Column-wise
import numpy as np
a=np.array([10,20,30,40,50,60]).reshape(2,3)
b=np.array([10,20,30,40,50,60]).reshape(2,3)
print("2d Array-1")
print(a)
print("2d Array-2")
print(b)
c=np.cumsum([a,b],axis=0)
print("Cummulative Sum")
print(c)

2d Array-1
[[10 20 30]
 [40 50 60]]
2d Array-2
[[10 20 30]
 [40 50 60]]
Cummulative Sum
[[[ 10  20  30]
  [ 40  50  60]]

 [[ 20  40  60]
  [ 80 100 120]]]


In [18]:
#Create an Object of 2d Arrays----Row-wise
import numpy as np
a=np.array([10,20,30,40,50,60]).reshape(2,3)
b=np.array([1,2,3,4,5,6]).reshape(2,3)
print("2d Array-1")
print(a)
print("2d Array-2")
print(b)
c=np.cumsum([a,b],axis=1)
print("Cummulative Sum")
print(c)

2d Array-1
[[10 20 30]
 [40 50 60]]
2d Array-2
[[1 2 3]
 [4 5 6]]
Cummulative Sum
[[[10 20 30]
  [50 70 90]]

 [[ 1  2  3]
  [ 5  7  9]]]
