In [2]:
#Create an Object of ndarray----2D Array
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Matrix-A")
print(a)
print("Dimension of a={}".format(a.ndim))
print("Shape of a={}".format(a.shape))
#Flatten the ndarray Object --- flatten()
b=a.flatten()
print("Matrix-B")
print(b)
print("Dimension of b={}".format(b.ndim))
print("Shape of b={}".format(b.shape))

Matrix-A
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of a=2
Shape of a=(3, 3)
Matrix-B
[10 20 30 40 50 60 70 80 90]
Dimension of b=1
Shape of b=(9,)


In [3]:
#Create an Object of ndarray---3D
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35,45,75,45,55]).reshape(2,4,2)
print("Matrix-A")
print(a)
print("Dimension of a={}".format(a.ndim))
print("Shape of a={}".format(a.shape))
#Flatten the ndarray Object --- flatten()
b=a.flatten()
print("Matrix-B")
print(b)
print("Dimension of b={}".format(b.ndim))
print("Shape of b={}".format(b.shape))

Matrix-A
[[[10 20]
  [30 40]
  [50 60]
  [70 80]]

 [[90 15]
  [25 35]
  [45 75]
  [45 55]]]
Dimension of a=3
Shape of a=(2, 4, 2)
Matrix-B
[10 20 30 40 50 60 70 80 90 15 25 35 45 75 45 55]
Dimension of b=1
Shape of b=(16,)


In [4]:
print("Address of a={}".format(id(a)))
print("Address of b={}".format(id(b)))

Address of a=2096550912496
Address of b=2096550913264


In [5]:
#Check the Base of flatten Array
print("Flatten Array Base=",b.base)

Flatten Array Base= None


In [6]:
print(a)

[[[10 20]
  [30 40]
  [50 60]
  [70 80]]

 [[90 15]
  [25 35]
  [45 75]
  [45 55]]]


In [8]:
#Update the Value of 30 
a[0][1][0]=33
print(a)

[[[10 20]
  [33 40]
  [50 60]
  [70 80]]

 [[90 15]
  [25 35]
  [45 75]
  [45 55]]]


In [9]:
print(b)

[10 20 30 40 50 60 70 80 90 15 25 35 45 75 45 55]


In [10]:
#Update the Last Value of Flatten Array b
b[-1]=550
print(b)

[ 10  20  30  40  50  60  70  80  90  15  25  35  45  75  45 550]


In [11]:
#Flatten the ndarray data by using ravel()
#Create an object of ndarray 
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
print("Matrix-A")
print(a)
print("Dimension of a={}".format(a.ndim))
print("Shape of a={}".format(a.shape))
#Flatten the ndarray Object --- ravel()
b=a.ravel()
print("Matrix-B")
print(b)
print("Dimension of b={}".format(b.ndim))
print("Shape of b={}".format(b.shape))

Matrix-A
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimension of a=2
Shape of a=(3, 3)
Matrix-B
[10 20 30 40 50 60 70 80 90]
Dimension of b=1
Shape of b=(9,)


In [12]:
print("Address of a={}".format(id(a)))
print("Address of b={}".format(id(b)))

Address of a=2096550914704
Address of b=2096550912496


In [14]:
#Do the changes on Both ndarray Object
a[0][0]=11
print(a)

[[11 20 30]
 [40 50 60]
 [70 80 90]]


In [15]:
print(a)
print("--------------------------")
print(b)

[[11 20 30]
 [40 50 60]
 [70 80 90]]
--------------------------
[11 20 30 40 50 60 70 80 90]


In [18]:
#Do the changes on Both ndarray Object
b[-1]=99
print(b)

[11 20 30 40 50 60 70 80 99]


In [19]:
print(a)
print("--------------------------")
print(b)

[[11 20 30]
 [40 50 60]
 [70 80 99]]
--------------------------
[11 20 30 40 50 60 70 80 99]


In [21]:
#Update 0th Row of ndarray a
a[0:1,:]=[100,200,300]
print(a)
print("--------------------------")
print(b)

[[100 200 300]
 [ 40  50  60]
 [ 70  80  99]]
--------------------------
[100 200 300  40  50  60  70  80  99]


In [22]:
b[-3:]=[700,800,900]
print(a)
print("--------------------------")
print(b)

[[100 200 300]
 [ 40  50  60]
 [700 800 900]]
--------------------------
[100 200 300  40  50  60 700 800 900]


In [23]:
#Create an object of ndarray 
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,15,25,35,45,75,45,55]).reshape(2,4,2)
print("Matrix-A")
print(a)
print("Dim of a=",a.ndim)
print("shape of a=",a.shape)
#flatten the ndarray Object
b=a.ravel()
print("Content of b")
print(b)
print("Dim of b=",b.ndim)
print("shape of b=",b.shape)

Matrix-A
[[[10 20]
  [30 40]
  [50 60]
  [70 80]]

 [[90 15]
  [25 35]
  [45 75]
  [45 55]]]
Dim of a= 3
shape of a= (2, 4, 2)
Content of b
[10 20 30 40 50 60 70 80 90 15 25 35 45 75 45 55]
Dim of b= 1
shape of b= (16,)


In [24]:
#Modify the Elements
#a[:,3:,1:]=[81,56]---ValueError: could not broadcast input array from shape (2,) into shape (2,1,1)

In [25]:
a[0][3][1]=81
a[1][3][1]=56
print(a)
print("----------------------")
print(b)

[[[10 20]
  [30 40]
  [50 60]
  [70 81]]

 [[90 15]
  [25 35]
  [45 75]
  [45 56]]]
----------------------
[10 20 30 40 50 60 70 81 90 15 25 35 45 75 45 56]
