In [2]:
#Using extract()
import numpy as np
a=np.array([1,2,3,4])
b=np.extract(a>2,a)
print("Array Elements")
print(b)

Array Elements
[3 4]


In [3]:
#Another Example
import numpy as np
a=np.array([1,2,3,4])
b=((a<2) | (a>3))
np.extract(b,a)

array([1, 4])

In [4]:
#Working with Missing Data
#It is common to encounter missing values encoded as NaN or None in real-world datasets.
#We can use filtering to remove or replace these missing values
import numpy as np
a=np.array([1,2,None,3,4])
#Replace missing values to 0
a=np.where(a==None,0,a)
print(a)

[1 2 0 3 4]


In [6]:
import numpy as np
a=np.array([1,2,None,3,4])
#Replace the missing values to 1
a=np.where(a==None,1,a)
print(a)

[1 2 1 3 4]


In [7]:
#By Using exctract() to ignore the missing values
import numpy as np
a=np.array([1,2,None,3,4])
a=np.extract(a!=None,a)
print(a)

[1 2 3 4]


In [8]:
#Data Cleaning
#Filtering functions enable removing unwanted outliers or invalid values
ages=np.array([15,99,87,21,67])
valid_ages=np.extract(ages<90,ages)
print(valid_ages)

[15 87 21 67]


In [10]:
#Reducing Memory Usage
array=np.random.rand(100000)
#Lots of memory  used to store full array
filtered=np.where(array<0.1,None,array)
#Less memory for extracted Elements
extracted=np.extract(array<0.1,array)
print("Number of Values with Filtered Array with where()=",len(filtered))
print("Number of Values with Extracted Array with extract()=",len(extracted))

Number of Values with Filtered Array with where()= 100000
Number of Values with Extracted Array with extract()= 10207
