In [1]:
#Create Two Matrices with 2D shape(2,2)
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]


In [2]:
#Syntax-- varname=numpy.add(ndarrayobj1,ndarryaobj2)

In [3]:
#Addition of Matrices---add()
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=np.add(a,b)   #add()
print("Matrix-C")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C
[[11 22]
 [33 44]]


In [4]:
#Alternatively, We Perform Addition of Matrices ---Arithmetic Operator "+"
#Syntax-- varname=ndarrayobj1+ndarrayobj2
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=a+b
print("Matrix-C")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C
[[11 22]
 [33 44]]


In [5]:
#Syntax-- varname=numpy.subtract(ndarrayobj1,ndarrayobj2)

In [6]:
#Subtraction of Matrices---subtract()
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=np.subtract(a,b)
print("Matrix-C")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C
[[ 9 18]
 [27 36]]


In [7]:
#Alternatively, We Perform Substraction of Matrices ---Arithmetic Operator "-"
#Syntax-- varname=ndarrayobj1-ndarrayobj2
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=a-b
print("Matrix-C")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C
[[ 9 18]
 [27 36]]


In [8]:
#Syntax-- varname=numpy.multiply(ndarrayobj1,ndarrayobj2)

In [9]:
#Multiplication of Matrices--- multiply()
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=np.multiply(a,b)
print("Matrix-C")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C
[[ 10  40]
 [ 90 160]]


In [10]:
#Alternatively, We Perform Multiplication of Matrices ---Arithmetic Operator "*"
#Syntax-- varname=ndarrayobj1*ndarrayobj2
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=a*b
print("Matrix-C")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C
[[ 10  40]
 [ 90 160]]


In [11]:
#Rule: Number of Columns in ndarray1 Must be equal to Number of rows in ndarray2
# Otherwise dot() or matmul() is Not Possible
#Syntax:   varname=numpy.dot(ndarray1,ndarray2)

In [12]:
#dot Product of Matrices ---dot() 
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=np.dot(a,b)
print("Matrix-C")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C
[[ 70 100]
 [150 220]]


In [13]:
#dot Product of Matrices ---matmul()
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=np.matmul(a,b)
print("Matrix-C")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C
[[ 70 100]
 [150 220]]


In [17]:
#dot Product of Matrices ---dot() 
import numpy as np
a=np.array([10,20,30,40,50,60]).reshape(2,3)
b=np.array([1,2,3,4,5,6]).reshape(3,2)
print("Matrix-A")
print(a,a.shape)
print("Matrix-B")
print(b,b.shape)
c=np.dot(a,b)
print("Matrix-C")
print(c,c.shape)

Matrix-A
[[10 20 30]
 [40 50 60]] (2, 3)
Matrix-B
[[1 2]
 [3 4]
 [5 6]] (3, 2)
Matrix-C
[[220 280]
 [490 640]] (2, 2)


In [18]:
#dot Product of Matrices ---matmul()
import numpy as np
a=np.array([10,20,30,40,50,60]).reshape(2,3)
b=np.array([1,2,3,4,5,6]).reshape(3,2)
print("Matrix-A")
print(a,a.shape)
print("Matrix-B")
print(b,b.shape)
c=np.matmul(a,b)
print("Matrix-C")
print(c,c.shape)

Matrix-A
[[10 20 30]
 [40 50 60]] (2, 3)
Matrix-B
[[1 2]
 [3 4]
 [5 6]] (3, 2)
Matrix-C
[[220 280]
 [490 640]] (2, 2)


In [19]:
#Synatx-- varname=numpy.divide(ndarrayobj1,ndarrayobj2)

In [20]:
#Division of Matrices---divide()
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=np.divide(a,b)
print("Matrix-C")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C
[[10. 10.]
 [10. 10.]]


In [21]:
#Division of Matrices ---divide()
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=np.divide(b,a)
print("Matrix-C--Division of Two Matrices")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C--Division of Two Matrices
[[0.1 0.1]
 [0.1 0.1]]


In [22]:
#Alternatively, We Perform Division of Matrices ---Arithmetic Operator "/"
#Syntax-- varname=ndarrayobj1/ndarrayobj2
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=a/b
print("Matrix-C")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C
[[10. 10.]
 [10. 10.]]


In [24]:
#Syntax:   varname=numpy.floor_divide(ndarray1,ndarray2)

In [25]:
#Division of Matrices ---floor_divide()
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=np.floor_divide(a,b)
print("Matrix-C--Floor Division of Two Matrices")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C--Floor Division of Two Matrices
[[10 10]
 [10 10]]


In [26]:
#Division of Matrices ---Arithmetic Operator //
#Syntax:   varname=ndarray1//ndarray2
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=a//b
print("Matrix-C--Floor Division of Two Matrices")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C--Floor Division of Two Matrices
[[10 10]
 [10 10]]


In [27]:
#Division of Matrices ---Arithmetic Operator //
#Syntax:   varname=ndarray1//ndarray2
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=b//a
print("Matrix-C--Floor Division of Two Matrices")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C--Floor Division of Two Matrices
[[0 0]
 [0 0]]


In [28]:
#Syntax:   varname=numpy.mod(ndarray1,ndarray2)

In [1]:
#Perform Modulo Division of Matrices ---mod()
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=np.mod(a,b)
print("Matrix-C--Modulo Division of Two Matrices")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C--Modulo Division of Two Matrices
[[0 0]
 [0 0]]


In [2]:
#Modulo Division of Matrices ---mod()
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=np.mod(b,a)
print("Matrix-C--Modulo Division of Two Matrices")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C--Modulo Division of Two Matrices
[[1 2]
 [3 4]]


In [3]:
#Modulo Division of Matrices ---Arithmetic Operator %
#Syntax:   varname=ndarray1%ndarray2
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=a%b  # Vector Based Operation
print("Matrix-C--Modulo Division of Two Matrices")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C--Modulo Division of Two Matrices
[[0 0]
 [0 0]]


In [4]:
#Modulo Division of Matrices ---Arithmetic Operator %
#Syntax:   varname=ndarray1%ndarray2
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=b%a  # Vector Based Operation
print("Matrix-C--Modulo Division of Two Matrices")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C--Modulo Division of Two Matrices
[[1 2]
 [3 4]]


In [5]:
#Syntax:   varname=numpy.power(ndarray1,ndarray2)

In [6]:
#Exponentiation of Matrices ---power()
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=np.power(a,b)
print("Matrix-C--Exponentiation of Two Matrices")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C--Exponentiation of Two Matrices
[[     10     400]
 [  27000 2560000]]


In [7]:
#Exponentiation of Matrices ---Arithmetic Exponentiation operator **
#Syntax:   varname=ndarray1**ndarray2
import numpy as np
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("Matrix-A")
print(a)
print("Matrix-B")
print(b)
c=a**b  # Vector Based Operation
print("Matrix-C--Exponentiation of Two Matrices")
print(c)

Matrix-A
[[10 20]
 [30 40]]
Matrix-B
[[1 2]
 [3 4]]
Matrix-C--Exponentiation of Two Matrices
[[     10     400]
 [  27000 2560000]]
