In [1]:
#Create an Object of 1darray---Discrete Differences
import numpy as np
a=np.array([10,28,35,49,5,6,70,85])
print("1D Array Data")
print(a)
b=np.diff(a)
print("Disecrete Difference of 1d Array=",b)

1D Array Data
[10 28 35 49  5  6 70 85]
Disecrete Difference of 1d Array= [ 18   7  14 -44   1  64  15]


In [6]:
#Create an Object of 1darray---Discrete Differences
import numpy as np
a=np.array([10,28,35,49,5,6,70,85])
print("1D Array Data")
print(a)
b=np.diff(a,n=1)
print("Discrete Difference of 1d Array=",b)

1D Array Data
[10 28 35 49  5  6 70 85]
Discrete Difference of 1d Array= [ 18   7  14 -44   1  64  15]


In [9]:
#Create an Object of 1darray---Discrete Differences
import numpy as np
a=np.array([10,28,35,49,5,6,70,85])
print("1D Array Data")
print(a)
da1=np.diff(a,n=1)
print("Discrete Difference of 1d Array=",da1)
da2=np.diff(da1,n=1)
print("Discrete Difference of 1d Array=",da2)

1D Array Data
[10 28 35 49  5  6 70 85]
Discrete Difference of 1d Array= [ 18   7  14 -44   1  64  15]
Discrete Difference of 1d Array= [-11   7 -58  45  63 -49]


In [10]:
#Create an Object of 1darray---Discrete Differences
import numpy as np
a=np.array([10,28,35,49,5,6,70,85])
print("1d Array Data")
print(a)
b=np.diff(a,n=2)
print("Discrete Difference of 1d Array=",b)

1d Array Data
[10 28 35 49  5  6 70 85]
Discrete Difference of 1d Array= [-11   7 -58  45  63 -49]


In [13]:
#Create an Object of 2darray---Discrete Differences
import numpy as np
a=np.array([10,28,35,49,5,6,70,85]).reshape(4,2)
print("2d Array Data")
print(a)
b=np.diff(a)
print("Discrete Difference of 2d Array\n",b)

2d Array Data
[[10 28]
 [35 49]
 [ 5  6]
 [70 85]]
Discrete Difference of 2d Array
 [[18]
 [14]
 [ 1]
 [15]]


In [14]:
#Create an Object of 2darray---Discrete Differences-----Column-wise
import numpy as np
a=np.array([10,28,35,49,5,6,70,85]).reshape(4,2)
print("2d Array Data")
print(a)
b=np.diff(a,axis=1)
print("Discrete Difference of 2d Array\n",b)

2d Array Data
[[10 28]
 [35 49]
 [ 5  6]
 [70 85]]
Discrete Difference of 2d Array
 [[18]
 [14]
 [ 1]
 [15]]


In [15]:
#Create an Object of 2darray---Discrete Differences-----Row-wise
import numpy as np
a=np.array([10,28,35,49,5,6,70,85]).reshape(4,2)
print("2d Array Data")
print(a)
b=np.diff(a,axis=0)
print("Discrete Difference of 2d Array\n",b)

2d Array Data
[[10 28]
 [35 49]
 [ 5  6]
 [70 85]]
Discrete Difference of 2d Array
 [[ 25  21]
 [-30 -43]
 [ 65  79]]


In [16]:
#Create an Object of 2darray---Discrete Differences----Column-wise
import numpy as np
a=np.array([10,28,35,49,5,6,70,85,20,11,22,33,44,55,21,16]).reshape(4,4)
print("2d Array Data")
print(a)
b=np.diff(a,axis=1)
print("Discrete Difference of 2d Array\n",b)

2d Array Data
[[10 28 35 49]
 [ 5  6 70 85]
 [20 11 22 33]
 [44 55 21 16]]
Discrete Difference of 2d Array
 [[ 18   7  14]
 [  1  64  15]
 [ -9  11  11]
 [ 11 -34  -5]]


In [17]:
#Create an Object of 2darray---Discrete Differences----Row-wise
import numpy as np
a=np.array([10,28,35,49,5,6,70,85,20,11,22,33,44,55,21,16]).reshape(4,4)
print("2d Array Data")
print(a)
b=np.diff(a,axis=0)
print("Discrete Difference of 2d Array\n",b)

2d Array Data
[[10 28 35 49]
 [ 5  6 70 85]
 [20 11 22 33]
 [44 55 21 16]]
Discrete Difference of 2d Array
 [[ -5 -22  35  36]
 [ 15   5 -48 -52]
 [ 24  44  -1 -17]]


In [18]:
#Create an Object of 2darray---Discrete Differences----Column-wise
import numpy as np
a=np.array([10,28,35,49,5,6,70,85,20,11,22,33,44,55,21,16]).reshape(4,4)
print("2d Array Data")
print(a)
b=np.diff(a,n=2,axis=1)
print("Discrete Difference of 2d Array\n",b)

2d Array Data
[[10 28 35 49]
 [ 5  6 70 85]
 [20 11 22 33]
 [44 55 21 16]]
Discrete Difference of 2d Array
 [[-11   7]
 [ 63 -49]
 [ 20   0]
 [-45  29]]


In [19]:
#Create an Object of 2darray---Discrete Differences----Row-wise
import numpy as np
a=np.array([10,28,35,49,5,6,70,85,20,11,22,33,44,55,21,16]).reshape(4,4)
print("2d Array Data")
print(a)
b=np.diff(a,n=2,axis=0)
print("Discrete Difference of 2d Array\n",b)

2d Array Data
[[10 28 35 49]
 [ 5  6 70 85]
 [20 11 22 33]
 [44 55 21 16]]
Discrete Difference of 2d Array
 [[ 20  27 -83 -88]
 [  9  39  47  35]]
