In [1]:
#Save the ndarray data into text File by using   numpy.savetxt()
import numpy as np
a=np.random.randint(2,10,size=(3,3))
print(a)
np.savetxt("F:\\Python-Libraries\\Numpy\\abc.data",a,delimiter=" ")
print("ndarray data saved in file---Verify")

[[2 8 5]
 [3 8 8]
 [3 7 8]]
ndarray data saved in file---Verify


In [11]:
#Read the ndarray data from file into the main memory--numpy.loadtxt()
import numpy as np
a=np.loadtxt("F:\\Python-Libraries\\Numpy\\abc.data",delimiter=" ")
print(a,type(a),a.dtype)
b=a.astype(int)
print(b,type(b),b.dtype)
c=b.astype("i1")
print(c,type(c),c.dtype)
d=c.astype("i2")
print(d,type(d),d.dtype)

[[2. 8. 5.]
 [3. 8. 8.]
 [3. 7. 8.]] <class 'numpy.ndarray'> float64
[[2 8 5]
 [3 8 8]
 [3 7 8]] <class 'numpy.ndarray'> int64
[[2 8 5]
 [3 8 8]
 [3 7 8]] <class 'numpy.ndarray'> int8
[[2 8 5]
 [3 8 8]
 [3 7 8]] <class 'numpy.ndarray'> int16


In [12]:
#Save the ndarray data into .npy  File by using   numpy.save()
import numpy as np
a=np.random.randint(2,10,size=(3,3))
print(a)
np.save("F:\\Python-Libraries\\Numpy\\nit.npy",a)
print("ndarray Data Saved in npy File---Verify")

[[6 2 5]
 [7 7 8]
 [6 8 5]]
ndarray Data Saved in npy File---Verify


In [17]:
#Save the ndarray data into .npy  File by using   numpy.save()
import numpy as np
a=np.random.randint(2,10,size=(3,3))
print(a)
b=np.load("F:\\Python-Libraries\\Numpy\\nit.npy")
print(b,type(b))
c=b.astype(float)
print(c,type(c),c.dtype)
d=c.astype("f2")
print(d,type(d),d.dtype)
e=d.astype("i1")
print(e,type(e),e.dtype)

[[9 7 4]
 [3 9 5]
 [5 7 4]]
[[6 2 5]
 [7 7 8]
 [6 8 5]] <class 'numpy.ndarray'>
[[6. 2. 5.]
 [7. 7. 8.]
 [6. 8. 5.]] <class 'numpy.ndarray'> float64
[[6. 2. 5.]
 [7. 7. 8.]
 [6. 8. 5.]] <class 'numpy.ndarray'> float16
[[6 2 5]
 [7 7 8]
 [6 8 5]] <class 'numpy.ndarray'> int8


In [27]:
#Save the Mutiple ndarray Objects  data into  single file .npz  File by using   numpy.savez()
import numpy as np
a=np.random.randint(10,20,size=6)
b=np.random.randint(100,200,size=(3,3))
c=np.random.randint(30,50,size=(2,3,3))
np.savez("F:\\Python-Libraries\\Numpy\\hyd.npz",r=a,u=b,k=c)
print("Ndarray Objects Saved in npz File--Verify")

Ndarray Objects Saved in npz File--Verify


In [28]:
#Read the Data from npz Files
import numpy as np
a=np.load("F:\\Python-Libraries\\Numpy\\hyd.npz")
print("Loaded Array")
print(a,type(a))

Loaded Array
NpzFile 'F:\\Python-Libraries\\Numpy\\hyd.npz' with keys: r, u, k <class 'numpy.lib.npyio.NpzFile'>


In [29]:
print("First  Ndarray={} Type={}  Dim={}".format(a["r"],type(a["r"]), a["r"].ndim))

First  Ndarray=[13 11 15 18 17 12] Type=<class 'numpy.ndarray'>  Dim=1


In [30]:
print("Second  Ndarray\n{} Type={}  Dim={}".format(a["u"],type(a["u"]), a["u"].ndim))

Second  Ndarray
[[150 179 116]
 [117 106 165]
 [134 120 159]] Type=<class 'numpy.ndarray'>  Dim=2


In [31]:
print("Third  Ndarray\n{} Type={}  Dim={}".format(a["k"],type(a["k"]), a["k"].ndim))

Third  Ndarray
[[[38 46 32]
  [48 36 48]
  [31 39 40]]

 [[49 41 43]
  [48 43 30]
  [32 44 39]]] Type=<class 'numpy.ndarray'>  Dim=3


In [36]:
#Save the Mutiple ndarray Objects  data into  single file .npz  File by using   numpy.savez()
import numpy as np
a=np.random.randint(10,20,size=6)
b=np.random.randint(100,200,size=(3,3))
c=np.random.randint(30,50,size=(2,3,3))
np.savez_compressed("F:\\Python-Libraries\\Numpy\\numpy.npz",r1=a,u2=b,k3=c)
print("Ndarray Objects Saved in npz File with Compressed--Verify")

Ndarray Objects Saved in npz File with Compressed--Verify


In [37]:
#Read the Compressed npz file data on the Basis of Key
a=np.load("F:\\Python-Libraries\\Numpy\\numpy.npz")
print("First  Ndarray={} Type={}  Dim={}".format(a["r1"],type(a["r1"]), a["r1"].ndim))
print("---------------------------------------")
print("Second  Ndarray\n{} Type={}  Dim={}".format(a["u2"],type(a["u2"]), a["u2"].ndim))
print("---------------------------------------")
print("Third  Ndarray\n{} Type={}  Dim={}".format(a["k3"],type(a["k3"]), a["k3"].ndim))

First  Ndarray=[14 10 13 17 19 17] Type=<class 'numpy.ndarray'>  Dim=1
---------------------------------------
Second  Ndarray
[[100 156 199]
 [198 189 116]
 [101 131 126]] Type=<class 'numpy.ndarray'>  Dim=2
---------------------------------------
Third  Ndarray
[[[39 34 46]
  [32 44 49]
  [40 42 33]]

 [[42 39 38]
  [32 31 31]
  [34 33 49]]] Type=<class 'numpy.ndarray'>  Dim=3
