In [12]:
#Create an Object of ndarray
import numpy as np
a=np.random.randint(100,150,size=10)
print("ndarray Object")
print(a)

ndarray Object
[143 109 117 144 144 126 113 127 125 109]


In [13]:
#Search for those Elements which are Divisible by 5
b=np.where(a%5==0)
print("Content of b={} Type={}".format(b[0],type(b[0])))

Content of b=[8] Type=<class 'numpy.ndarray'>


In [14]:
a[b[0]]

array([125], dtype=int32)

In [15]:
#Search for those Elements which are Divisible by 5
b=np.extract(a%5==0,a)
print("Content of b={} Type={}".format(b,type(b)))

Content of b=[125] Type=<class 'numpy.ndarray'>


In [17]:
#Another Example 
import numpy as np
a=np.array([10,15,20,25,30])
result=np.where(a>20)
print("Indices=",result)
print("Data=",a[result])

Indices= (array([3, 4]),)
Data= [25 30]


In [19]:
import numpy as np
a=np.array([2,7,8,3,10])
idx=np.where(a%2==0)  #Here idx is a boolean array
print(idx) #Indices are given
print("Even Numbers:",a[idx])  #Values are Shown

(array([0, 2, 4]),)
Even Numbers: [ 2  8 10]


In [20]:
nda=np.array([60,40,55,45,70,45,38,66])
ns=np.where(nda>=50,nda,"Vacant")
print(ns)

['60' 'Vacant' '55' 'Vacant' '70' 'Vacant' 'Vacant' '66']


In [21]:
nda=np.array([1000,2000,3000,450,550,500,750,5000])
nss=np.where(nda<=1000,nda+nda*50/100,nda)
print(nss)

[1500. 2000. 3000.  675.  825.  750. 1125. 5000.]


In [22]:
#We can also use arrays for any of the arguments. Here we provide array values for x and y
a=np.array([1,2,3,4])
x=np.array([10,20,30,40])
y=np.array([100,200,300,400])
z=np.where(a>2,x,y)
print(z)

[100 200  30  40]


In [23]:
#Converting into zero
import numpy as np
a=np.array([1,2,3,4])
x=np.where((a<2)|(a>3),0,a)
print(x)

[0 2 3 0]


In [25]:
#Bitwise & Condition
import numpy as np
a=np.array([1,2,3,4])
x=np.where((a>=2)&(a<=3))
print(a[x])

[2 3]


In [26]:
import numpy as np
a = np.array([1, 2, 3, 4])
x=np.where( (a >= 2) & (a <=3 ) ,  True ,  False)
print(x) # Output------array([0, 2, 3, 0])
print(a[x])

[False  True  True False]
[2 3]
