In [1]:
#Create an object of ndarray Array
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8])
print("1d Array Data")
print(a)

1d Array Data
[10  2 13  4 14  5 15 18  8]


In [2]:
#Syntax:  varname=numpy.amax(ndarray,axis)

In [3]:
#Find Max Element from 1D Array
#Find Highest Element in 1DArray---amax()
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8])
print("1d Array Data")
print(a)
maxv=np.amax(a)
print("Maximum Element=",maxv)

1d Array Data
[10  2 13  4 14  5 15 18  8]
Maximum Element= 18


In [4]:
#Find Max Element from 2D Array
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8]).reshape(3,3)
print("2d Array Elements")
print(a)
maxv=np.amax(a)
print("Max Element=",maxv)

2d Array Elements
[[10  2 13]
 [ 4 14  5]
 [15 18  8]]
Max Element= 18


In [5]:
#Find Max Element from 2D Array in Column-wise
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8]).reshape(3,3)
print("2d Array Elements")
print(a)
maxv=np.amax(a)
colmaxv=np.amax(a,axis=0)  # Here axis=0 Represents Columns
print("Max Element=",maxv)
print("Column Max Elements=",colmaxv)

2d Array Elements
[[10  2 13]
 [ 4 14  5]
 [15 18  8]]
Max Element= 18
Column Max Elements= [15 18 13]


In [6]:
#Find Max Elements from 2D Array in Row-wise
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8]).reshape(3,3)
print("2d Array Elements")
print(a)
maxv=np.amax(a)
rowmaxv=np.amax(a,axis=1)  # Here axis=1 Represents Rows
print("Max Element=",maxv)
print("Row Max Elements=",rowmaxv)

2d Array Elements
[[10  2 13]
 [ 4 14  5]
 [15 18  8]]
Max Element= 18
Row Max Elements= [13 14 18]


In [7]:
#Syntax:  varname=numpy.amin(ndarray,axis)

In [8]:
#Find Min Element from 1D Array
#Find Smallest Element in 1DArray---amin()
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8])
print("1d Array Elements")
print(a)
minv=np.amin(a)
print("Min Element=",minv)

1d Array Elements
[10  2 13  4 14  5 15 18  8]
Min Element= 2


In [9]:
#Find Min Element from 1D Array in Column-wise
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8]).reshape(3,3)
print("2d Array Elements")
print(a)
minv=np.amin(a)
colminv=np.amin(a,axis=0) # Here axis=0 Represents Cols
print("Min Element=",minv)
print("Column Min Values=",colminv)

2d Array Elements
[[10  2 13]
 [ 4 14  5]
 [15 18  8]]
Min Element= 2
Column Min Values= [4 2 5]


In [10]:
#Find Min Element from 1D Array in Row-wise
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8]).reshape(3,3)
print("2d Array Elements")
print(a)
minv=np.amin(a)
rowminv=np.amin(a,axis=1) # Here axis=1 Represents Rows
print("Min Element=",minv)
print("Row Min Values=",rowminv)

2d Array Elements
[[10  2 13]
 [ 4 14  5]
 [15 18  8]]
Min Element= 2
Row Min Values= [2 4 8]


In [11]:
#Find Min Element from 3D Array in Row-wise
import numpy as np
a=np.array([10,2,13,4,14,5,15,18,8,12,9,10,25,8,4,14]).reshape(2,4,2)
print("3d Array Elements")
print(a)
maxv=np.amax(a)
print("Max Element=",maxv)
Fcolmaxv=np.amax(a[0],axis=0)
Scolmaxv=np.amax(a[1],axis=0)
print("First Matrix Col Max Vals\n",Fcolmaxv)
print("Second Matrix Col Max Vals\n",Scolmaxv)

3d Array Elements
[[[10  2]
  [13  4]
  [14  5]
  [15 18]]

 [[ 8 12]
  [ 9 10]
  [25  8]
  [ 4 14]]]
Max Element= 25
First Matrix Col Max Vals
 [15 18]
Second Matrix Col Max Vals
 [25 14]


In [12]:
#Finding the Mean of ndarray Elements--mean()
#Syntax: varname=numpy.mean(ndarray,axis)

In [13]:
#Consider ndarray and find mean
import numpy as np
a=np.array([2,3,1,4])
print("1D Array Data")
print(a)
mv=np.mean(a)
print("Mean of 1DArray=",mv)

1D Array Data
[2 3 1 4]
Mean of 1DArray= 2.5


In [14]:
#Consider 2darray and find mean with row and column
import numpy as np
a=np.array([2,3,1,4]).reshape(2,2)
print("2D Array Data")
print(a)
mv=np.mean(a)
colmean=np.mean(a,axis=0) # Here axis=0 Represents Cols
rowmean=np.mean(a,axis=1) # Here axis=1 Represents Rows
print("Mean of 2D Array=",mv)
print("Column-wise mean=",colmean)
print("Row-wise mean=",rowmean)

2D Array Data
[[2 3]
 [1 4]]
Mean of 2D Array= 2.5
Column-wise mean= [1.5 3.5]
Row-wise mean= [2.5 2.5]


In [15]:
#Consider 2darray and find mean with row and column
import numpy as np
a=np.random.randint(100,200,size=(4,7))
print("2D Array Data")
print(a)
mv=np.mean(a)
colmean=np.mean(a,axis=0)
rowmean=np.mean(a,axis=1)
print("Mean of 2D Array=",mv)
print("Column-wise mean=",colmean)
print("Row-wise mean=",rowmean)

2D Array Data
[[131 187 146 115 157 107 170]
 [121 190 104 105 196 182 159]
 [148 129 192 110 112 140 164]
 [195 168 110 165 109 104 153]]
Mean of 2D Array= 145.32142857142858
Column-wise mean= [148.75 168.5  138.   123.75 143.5  133.25 161.5 ]
Row-wise mean= [144.71428571 151.         142.14285714 143.42857143]


In [16]:
#Consider the following 2darray and find mean
import numpy as np
a=np.random.randint(2,10,size=(3,3))
print("2D Array Data")
print(a)

2D Array Data
[[4 9 9]
 [7 3 4]
 [4 6 8]]


In [18]:
#Find the Mean of Opp Principle Diagnoal Elements
import numpy as np
pd=np.diag(a)
print("Principle Diagonal Elements=",pd)
pdmv=np.mean(pd)
print("Mean of Principle Diagonal Elements=",pdmv)

Principle Diagonal Elements= [4 3 8]
Mean of Principle Diagonal Elements= 5.0


In [20]:
#Find the Mean of Opposite Principle Diagonal Elements
import numpy as np
a=np.random.randint(2,10,size=(3,3))
print("2D Array Data")
print(a)
b=a[[0,1,2],[2,1,0]]
print("Opposite Principle Diagonals")
mv=np.mean(b)
print("Mean of Opposite Principle Diagonal Elements=",mv)

2D Array Data
[[4 5 2]
 [9 4 6]
 [3 9 7]]
Opposite Principle Diagonals
Mean of Opposite Principle Diagonal Elements= 3.0


In [21]:
#Syntax:   vraname=numpy.median(ndarray,axis)

In [26]:
#Find  the Median of ndarray---median()
a=np.random.randint(1,50,size=7)
print("1D Array Data")
print(a)

1D Array Data
[48 30 17 44 23 43 33]


In [27]:
#Median  of 1D Array of odd Number of Elements
mdv=np.median(a)
print("Median of 1D Array=",mdv)

Median of 1D Array= 33.0


In [28]:
#Median  of 1D Array of Even Number of Elements
a=np.random.randint(12,50,size=8)
print("1D Array Data")
print(a)
mdv=np.median(a)
print("Median of 1D Array=",mdv)

1D Array Data
[31 24 23 33 40 27 25 42]
Median of 1D Array= 29.0


In [29]:
a=np.random.randint(12,50,size=(3,3))
print("2D Array Data")
print(a)

2D Array Data
[[37 18 47]
 [23 33 35]
 [45 29 26]]


In [30]:
#Median of 2D
import numpy as np
mv=np.median(a)
colmv=np.median(a,axis=0)
rowmv=np.median(a,axis=1)
print("Median Value=",mv)
print("Column Median=",colmv)
print("Row Median=",rowmv)

Median Value= 33.0
Column Median= [37. 29. 35.]
Row Median= [37. 33. 29.]


In [31]:
#Variance of ndarray---1D Array
import numpy as np
a=np.array([2,3,1,4])
print("1D Array Data")
print(a)
v=np.var(a)
print("Variance of a=",v)

1D Array Data
[2 3 1 4]
Variance of a= 1.25


In [32]:
#Variance of ndarray----2D Array
import numpy as np
a=np.array([2,3,1,4]).reshape(2,2)
print("2D Array Data")
print(a)
v=np.var(a)
colv=np.var(a,axis=0)
rowv=np.var(a,axis=1)
print("Variance of a=",v)
print("Column Variance=",colv)
print("Row Variance=",rowv)

2D Array Data
[[2 3]
 [1 4]]
Variance of a= 1.25
Column Variance= [0.25 0.25]
Row Variance= [0.25 2.25]


In [33]:
#Standard Deviation= sqrt(var) of ndarray----1D Array
import numpy as np
a=np.array([2,3,1,4])
print("1D Array Data")
print(a)
d=np.std(a)
print("Standard Deviation=",d)

1D Array Data
[2 3 1 4]
Standard Deviation= 1.118033988749895


In [34]:
#Standard Deviation= sqrt(var) of ndarray----2D Array
import numpy as np
a=np.array([2,3,1,4]).reshape(2,2)
print("1D Array Data")
print(a)
d=np.std(a)
cold=np.std(a,axis=0)
rowd=np.std(a,axis=1)
print("Standard Deviation of a=",d)
print("Column Standard Deviation=",cold)
print("Row Standard Deviation=",rowd)

1D Array Data
[[2 3]
 [1 4]]
Standard Deviation of a= 1.118033988749895
Column Standard Deviation= [0.5 0.5]
Row Standard Deviation= [0.5 1.5]


In [35]:
#Standard Deviation= sqrt(var) of ndarray----2D Array
import numpy as np
a=np.random.randint(10,20,size=(3,3))
print("2D Array Data")
print(a)
d=np.std(a)
cold=np.std(a,axis=0)
rowd=np.std(a,axis=1)
print("Standard Deviation of a=",d)
print("Column Standard Deviation=",cold)
print("Row Standard Deviation=",rowd)

2D Array Data
[[16 11 16]
 [19 10 16]
 [12 18 11]]
Standard Deviation of a= 3.1622776601683795
Column Standard Deviation= [2.86744176 3.55902608 2.3570226 ]
Row Standard Deviation= [2.3570226  3.74165739 3.09120617]
