In [1]:
#Create an Object of 1D Array
import numpy as np
a=np.array([1,2,3,4])
b=np.prod(a)
print("Original Array Data")
print(a)
print("Product=",b)

Original Array Data
[1 2 3 4]
Product= 24


In [2]:
#Create an Object of 1D Arrays
import numpy as np
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
c=np.prod([a,b])
print("Original Array Data-1")
print(a)
print("Original Array Data-2")
print(b)
print("Product=",c)

Original Array Data-1
[1 2 3 4]
Original Array Data-2
[1 2 3 4]
Product= 576


In [3]:
#Create an Object of 1D Arrays---Column-wise
import numpy as np
a=np.array([1,2,3])
b=np.array([1,2,3])
c=np.prod([a,b],axis=0)
print("Original Array Data-1")
print(a)
print("Original Array Data-2")
print(b)
print("Product=",c)

Original Array Data-1
[1 2 3]
Original Array Data-2
[1 2 3]
Product= [1 4 9]


In [4]:
#Create an Object of 1D Arrays----Row-wise
import numpy as np
a=np.array([1,2,3])
b=np.array([1,2,3])
c=np.prod([a,b],axis=1)
print("Original Array Data-1")
print(a)
print("Original Array Data-2")
print(b)
print("Product=",c)

Original Array Data-1
[1 2 3]
Original Array Data-2
[1 2 3]
Product= [6 6]


In [5]:
#Create an Object of 2D Array
import numpy as np
a=np.array([1,2,3,4,5,6]).reshape(2,3)
print("Original Array Data")
print(a)
b=np.prod(a)
print("Product=",b)

Original Array Data
[[1 2 3]
 [4 5 6]]
Product= 720


In [7]:
#Create an Object of 2D Array----Column-wise
import numpy as np
a=np.array([1,2,3,4,5,6]).reshape(2,3)
print("Original Array Data")
print(a)
b=np.prod(a,axis=0)
print("Product=",b)

Original Array Data
[[1 2 3]
 [4 5 6]]
Product= [ 4 10 18]


In [8]:
#Create an Object of 2D Array
import numpy as np
a=np.array([1,2,3,4,5,6]).reshape(2,3)
print("Original Array Data")
print(a)
b=np.prod(a,axis=1)
print("Product=",b)

Original Array Data
[[1 2 3]
 [4 5 6]]
Product= [  6 120]


In [10]:
#Create an Object of 2D Arrays----Column-wise
import numpy as np
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
c=np.prod([a,b],axis=0)
print("Original Array Data-1")
print(a)
print("Original Array Data-2")
print(b)
print("Product\n",c)

Original Array Data-1
[[1 2]
 [3 4]]
Original Array Data-2
[[1 2]
 [3 4]]
Product
 [[ 1  4]
 [ 9 16]]


In [2]:
#Create an Object of 2D Arrays----Row-wise
import numpy as np
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
c=np.prod([a,b],axis=1)
print("Original Array Data-1")
print(a)
print("original Array Data-2")
print(b)
print("Product\n",c)

Original Array Data-1
[[1 2]
 [3 4]]
original Array Data-2
[[1 2]
 [3 4]]
Product
 [[3 8]
 [3 8]]


In [3]:
#cumprod()
#Create an object of 1darray
import numpy as np
a=np.array([1,2,3,4])
b=np.cumprod(a)
print("Original 1d Array")
print(a)
print("Cumulative Product=",b)

Original 1d Array
[1 2 3 4]
Cumulative Product= [ 1  2  6 24]


In [4]:
#Create an Object of 1D Arrays
import numpy as np
a=np.array([1,2,3])
b=np.array([1,2,3])
c=np.cumprod([a,b])
print("Original 1d Array-1")
print(a)
print("Original 1d Array-2")
print(b)
print("Cumulative Product\n",c)

Original 1d Array-1
[1 2 3]
Original 1d Array-2
[1 2 3]
Cumulative Product
 [ 1  2  6  6 12 36]


In [6]:
#Create an Object of 1D Arrays----Column-wise
import numpy as np
a=np.array([1,2,3])
b=np.array([1,2,3])
c=np.cumprod([a,b],axis=0)
print("Original 1d Array-1")
print(a)
print("Original 1d Array-2")
print(b)
print("Cumulative Product\n",c)

Original 1d Array-1
[1 2 3]
Original 1d Array-2
[1 2 3]
Cumulative Product
 [[1 2 3]
 [1 4 9]]


In [7]:
#Create an Object of 1D Arrays----Row-wise
import numpy as np
a=np.array([1,2,3])
b=np.array([1,2,3])
c=np.cumprod([a,b],axis=1)
print("Original 1d Array-1")
print(a)
print("Original 1d Array-2")
print(b)
print("Cumulative Product\n",c)

Original 1d Array-1
[1 2 3]
Original 1d Array-2
[1 2 3]
Cumulative Product
 [[1 2 6]
 [1 2 6]]


In [8]:
#Create 2d Array Object
import numpy as np
a=np.array([1,2,3,4,5,6]).reshape(2,3)
print("2D Array ")
print(a)
b=np.cumprod(a)
print("Cumulative Product",b)

2D Array 
[[1 2 3]
 [4 5 6]]
Cumulative Product [  1   2   6  24 120 720]


In [9]:
#Create an Object of 2D Array----Column-wise
import numpy as np
a=np.array([1,2,3,4,5,6]).reshape(3,2)
print("2D Array ")
print(a)
b=np.cumprod(a,axis=0)
print("Cumulative Product\n",b)

2D Array 
[[1 2]
 [3 4]
 [5 6]]
Cumulative Product
 [[ 1  2]
 [ 3  8]
 [15 48]]


In [10]:
#Create an Object of 2D Array----Row-wise
import numpy as np
a=np.array([1,2,3,4,5,6]).reshape(2,3)
print("2D Array ")
print(a)
b=np.cumprod(a,axis=1)
print("Cumulative Product\n",b)

2D Array 
[[1 2 3]
 [4 5 6]]
Cumulative Product
 [[  1   2   6]
 [  4  20 120]]


In [11]:
#Create an Object of 2D Arrays----Column-wise
import numpy as np
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("2D Array-1")
print(a)
print("2D Array-2")
print(b)
c=np.cumprod([a,b],axis=0)
print("Cumulative Product\n",c)

2D Array-1
[[1 2]
 [3 4]]
2D Array-2
[[1 2]
 [3 4]]
Cumulative Product
 [[[ 1  2]
  [ 3  4]]

 [[ 1  4]
  [ 9 16]]]


In [12]:
#Create an Object of 2D Arrays----Row-wise
import numpy as np
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
print("2D Array-1")
print(a)
print("2D Array-2")
print(b)
c=np.cumprod([a,b],axis=1)
print("Cumulative Product\n",c)

2D Array-1
[[1 2]
 [3 4]]
2D Array-2
[[1 2]
 [3 4]]
Cumulative Product
 [[[1 2]
  [3 8]]

 [[1 2]
  [3 8]]]
