In [1]:
#Finding Unique Elements from ndarray---numpy.unique()
import numpy as np
a=np.array([1,1,1,2,3,4,5,5,5,6])
b=np.unique(a)
print(b)

[1 2 3 4 5 6]


In [2]:
#Finding the Union of two ndarray Objects--numpy.union1d()
import numpy as np
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
c=np.union1d(a,b)
print(c)

[1 2 3 4 5 6]


In [4]:
#Finding the Intersection of two ndarray Objects--numpy.intersect1d()
import numpy as np
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
c=np.intersect1d(a,b)
print(c,type(c))

[3 4] <class 'numpy.ndarray'>


In [5]:
#Finding the Difference  of two ndarray Objects--numpy.setdiff1d()
import numpy as np
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
c=np.setdiff1d(a,b)
print(c)

[1 2]


In [6]:
#Finding the Difference  of two Ndarray Objects--numpy.setdiff1d()
import numpy as np
a=np.array([1,2,3,4])
b=np.array([3,4,5,6])
c=np.setdiff1d(a,b)
print(c,type(c))

[1 2] <class 'numpy.ndarray'>


In [12]:
#Finding the Difference  of two Ndarray Objects--numpy.setdiff1d()
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,1,2])
newarr=np.setdiff1d(arr1,arr2)
print(newarr,type(newarr))

[] <class 'numpy.ndarray'>


In [13]:
#Finding the symmetric difference ff two Ndarray Objects--numpy.setxor1d()
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
newarr=np.setxor1d(arr1,arr2)
print(newarr)

[1 2 5 6]


In [16]:
#Finding the symmetric difference ff two Ndarray Objects--numpy.setxor1d()
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,1,2])
newarr=np.setxor1d(arr1,arr2)
print(newarr,type(newarr))

[] <class 'numpy.ndarray'>
