In [1]:
# rand()-----> This Function Generates random sample(s) between 0.0 to 1.0---> Maths [0.0 , 1.0)
#varname=numpy.random.rand()
#varname=numpy.random.rand(Value)
#varname=numpy.random.rand(Rows, Cols)
#varname=numpy.random.rand(No. of Matrices,Rows, Cols)

In [21]:
from numpy import random as r
val=r.rand()
print("Random Sample={} Type={}".format(val,type(val)))

Random Sample=0.9753073342306855 Type=<class 'float'>


In [22]:
from numpy import random as r
val=r.rand()
print("Random Sample={} Type={}".format(val,type(val)))

Random Sample=0.43970221490897965 Type=<class 'float'>


In [23]:
#Generate 5 Random sample for Uniform Distribution 
from numpy import random as r
val=r.rand(5)
print("Random Samples={} Type={}".format(val,type(val)))

Random Samples=[0.18901077 0.68416789 0.34295534 0.3522171  0.73288592] Type=<class 'numpy.ndarray'>


In [24]:
#Generate 10 Random Samples For Uniform Distribution
from numpy import random as r
val=r.rand(10)
print("Random Samples={} Type={}".format(val,type(val)))

Random Samples=[0.62898352 0.0623867  0.47946307 0.46717374 0.01055677 0.98858017
 0.8037333  0.58097775 0.99565329 0.43536992] Type=<class 'numpy.ndarray'>


In [25]:
#Generate  2D Random sample for Uniform Distribution with 3 Rows and 3 Cols
from numpy import random as r
val=r.rand(3,3)
print("Random Samples={} Type={}".format(val,type(val)))
print("Dimension of a={} Shape={}".format(val.ndim,val.shape))

Random Samples=[[0.56458378 0.40531195 0.77520614]
 [0.97453608 0.4295124  0.79480123]
 [0.96359236 0.92461716 0.12689197]] Type=<class 'numpy.ndarray'>
Dimension of a=2 Shape=(3, 3)


In [26]:
#Generate  2D Random sample for Uniform Distribution with 3 Rows and 2 Cols
from numpy import random as r
val=r.rand(3,2)
print("Random Samples={} Type={}".format(val,type(val)))
print("Dimesnion of a={} Shape={}".format(val.ndim,val.shape))

Random Samples=[[0.28757756 0.82454807]
 [0.0213187  0.3822704 ]
 [0.43083358 0.88706825]] Type=<class 'numpy.ndarray'>
Dimesnion of a=2 Shape=(3, 2)


In [27]:
#Generate  3D Random sample for Uniform Distribution with 2 Matrices along  3 Rows and 2 Cols
from numpy import random as r
val=r.rand(2,3,2)
print("Random Samples={} Type={}".format(val,type(val)))
print("Dimension of a={} Shape={}".format(val.ndim,val.shape))

Random Samples=[[[0.57645217 0.73959415]
  [0.0371032  0.91211993]
  [0.81885426 0.1962801 ]]

 [[0.80511355 0.33413933]
  [0.57815428 0.62604072]
  [0.50120495 0.79159296]]] Type=<class 'numpy.ndarray'>
Dimension of a=3 Shape=(2, 3, 2)


In [28]:
#Flatten the Data of 3 Dimension
val.shape=(12,)
print(val)

[0.57645217 0.73959415 0.0371032  0.91211993 0.81885426 0.1962801
 0.80511355 0.33413933 0.57815428 0.62604072 0.50120495 0.79159296]


In [31]:
#Re-Shapping the Data
val=val.reshape(3,4)
print(val)

[[0.57645217 0.73959415 0.0371032  0.91211993]
 [0.81885426 0.1962801  0.80511355 0.33413933]
 [0.57815428 0.62604072 0.50120495 0.79159296]]


In [36]:
from numpy import random as r
val=r.rand(2,3,2)
print("Random Samples={} Type={}".format(val,type(val)))
print("Dimension of a={} Shape={}".format(val.ndim,val.shape))

Random Samples=[[[0.6656018  0.23783699]
  [0.73843895 0.35667105]
  [0.8646326  0.40512169]]

 [[0.36713657 0.3674163 ]
  [0.82290953 0.85004269]
  [0.92873254 0.94468008]]] Type=<class 'numpy.ndarray'>
Dimension of a=3 Shape=(2, 3, 2)


In [38]:
for v in val.flatten():
    print(v)

0.6656017983828312
0.2378369925041186
0.7384389488655405
0.3566710481336498
0.8646325972511755
0.40512168532387316
0.3671365707389622
0.36741630119628443
0.8229095304223967
0.8500426928512748
0.9287325404627178
0.9446800752037184


In [43]:
for v in  val.flatten():
    print("%0.2f" %v)

0.67
0.24
0.74
0.36
0.86
0.41
0.37
0.37
0.82
0.85
0.93
0.94


In [44]:
#uniform()  :  Uniform Distribution
#------------------------------------------------------------------------
#This Function Generates random sample(s) between Two Intervals(Low,High) According Programmer Choice.
#The Default random sample is low is 0.0 and high is 1.0
#Syntax-1:      varname=numpy.random.uniform()
#Syntax-2:	   varname=numpy.random.uniform(Low,High)	
#Syntax-3:	   varname=numpy.random.uniform(Low,High,size)

In [45]:
#Generate One Random Sample Value between 0.0 to 1.0 with uniform()
from numpy import random as r
val=r.uniform()
print("Random Sample={} Type={}".format(val,type(val)))

Random Sample=0.712576003824 Type=<class 'float'>


In [46]:
from numpy import random as r
val=r.uniform()
print("Random Sample={} Type={}".format(val,type(val)))

Random Sample=0.9490174647528031 Type=<class 'float'>


In [47]:
from numpy import random as r
val=r.uniform(size=5)
print("Random Sample={} Type={}".format(val,type(val)))

Random Sample=[0.21533809 0.39290643 0.17273708 0.83242278 0.83026844] Type=<class 'numpy.ndarray'>


In [48]:
from numpy import random as r
val=r.uniform(10,12)
print("Random Sample={} Type={}".format(val,type(val)))

Random Sample=10.291147559230206 Type=<class 'float'>


In [49]:
from numpy import random as r
val=r.uniform(10.5,12)
print("Random Sample={} Type={}".format(val,type(val)))

Random Sample=10.920121021217682 Type=<class 'float'>


In [50]:
from numpy import random as r
val=r.uniform(10,12,5)
print("Random Sample={} Type={}".format(val,type(val)))

Random Sample=[11.0584435  11.89924382 10.12439816 11.05458938 10.1146245 ] Type=<class 'numpy.ndarray'>


In [52]:
from numpy import random as r
val=r.uniform(100,111,(3,3))
print("Random Sample={} Type={}".format(val,type(val)))
print("Dimension of val={} Shape={}".format(val.ndim,val.shape))

Random Sample=[[108.37274155 101.68914868 108.81423908]
 [107.4507561  104.85542361 100.41779387]
 [101.1652084  101.8327352  104.90779295]] Type=<class 'numpy.ndarray'>
Dimension of val=2 Shape=(3, 3)


In [53]:
from numpy import random as r
val=r.uniform(100,111,(2,2,2))
print("Random Sample={} Type={}".format(val,type(val)))
print("Dimension of val={} Shape={}".format(val.ndim,val.shape))

Random Sample=[[[110.87374509 105.76059417]
  [101.28722804 105.12217952]]

 [[106.64393224 108.87199095]
  [106.52659267 105.62440666]]] Type=<class 'numpy.ndarray'>
Dimension of val=3 Shape=(2, 2, 2)
