In [1]:
#Syntax-1---varname=numpy.random.randn()------->Gives Random Floating Point Values

In [3]:
import numpy.random as r
a=r.randn()
print("Randon Floating Values={} Type={}".format(a,type(a)))

Randon Floating Values=1.209866286063475 Type=<class 'float'>


In [4]:
import numpy.random as r
a=r.randn()
print("Randon Floating Values={} Type={}".format(a,type(a)))

Randon Floating Values=-0.7452667535667997 Type=<class 'float'>


In [5]:
import numpy.random as r
a=r.randn()
print("Randon Floating Values={} Type={}".format(a,type(a)))

Randon Floating Values=-1.3428854927039373 Type=<class 'float'>


In [6]:
#Get 5 Random Floating Point Values
for i in range(0,6):
    a=r.randn()
    print("Randon Floating Values={} Type={}".format(a,type(a)))

Randon Floating Values=1.2289840991962708 Type=<class 'float'>
Randon Floating Values=-1.0602623342310138 Type=<class 'float'>
Randon Floating Values=-0.0962825386528642 Type=<class 'float'>
Randon Floating Values=-1.6128619475504933 Type=<class 'float'>
Randon Floating Values=-0.8143082409464465 Type=<class 'float'>
Randon Floating Values=1.3973468343331286 Type=<class 'float'>


In [7]:
#Syntax-2---varname=numpy.random.randn(Value)
#Gives  Number of Random Floating Point Values Depends on 'Value'-- +VE OR -VE---1D

In [8]:
import numpy.random as r
a=r.randn(6)
print("Randon Floating Values={} Type={}".format(a,type(a)))

Randon Floating Values=[-1.24208749 -1.19539231 -1.06453767  2.40406781  0.41450321  1.36361605] Type=<class 'numpy.ndarray'>


In [10]:
import numpy.random as r
a=r.randn(6)
print("Randon Floating Values={} Type={}".format(a,type(a)))
print("Dimension of a={} Shape={}".format(a.ndim,a.shape))

Randon Floating Values=[-0.43041649  1.10123783  0.64542742  0.41073538  1.69201404  0.33084863] Type=<class 'numpy.ndarray'>
Dimension of a=1 Shape=(6,)


In [11]:
#Syntax-3-----varname=numpy.random.randn(Rows,Cols)
#Gives  Number of Random Floating Point Values Depends on 'Rows x Cols'-- +VE OR -VE---2D

In [12]:
#Creating For 2 Dimension
import numpy.random as r
a=r.randn(3,3)
print("Randon Floating Values={} Type={}".format(a,type(a)))
print("Dimension of a={} Shape={}".format(a.ndim,a.shape))

Randon Floating Values=[[-0.35800018  0.30169317  0.1203053 ]
 [ 0.62147649 -1.05408627 -0.93698188]
 [-1.23367613  0.86010712 -0.50403129]] Type=<class 'numpy.ndarray'>
Dimension of a=2 Shape=(3, 3)


In [13]:
#Creating For 2 Dimension
import numpy.random as r
a=r.randn(6,6)
print("Random Floating Values={} Type={}".format(a,type(a)))
print("Dimesnion of a={} Shape={}".format(a.ndim,a.shape))

Random Floating Values=[[ 0.26890432 -0.44607279  0.04734446  1.11405846  1.12364897 -0.26398675]
 [-0.51115958 -0.04166627 -0.51667193 -0.15339988 -0.22441887  0.80528908]
 [ 0.1625318  -0.3691674  -1.4947823   0.22884858  1.15388124 -0.02911419]
 [ 0.32603883  0.96259565  0.47410694 -0.2678886  -0.9276477  -1.77881426]
 [ 2.01794448 -0.67627378 -1.11130751  0.00983334  0.78672821  0.42919795]
 [-1.98529571 -0.64536285  1.6279867   0.64782364  1.31123076 -1.53660138]] Type=<class 'numpy.ndarray'>
Dimesnion of a=2 Shape=(6, 6)


In [14]:
#Synatx-3----varname=numpy.random.randn(Matrices,Rows,Columns)
#Gives  Number of Random Floating Point Values Depends on 'Matrices x Rows x Cols'-- +VE OR -VE---3D

In [15]:
import numpy.random as r
a=r.randn(2,3,3)
print("Random Floating Values={} Type={}".format(a,type(a)))
print("Dimension of a={} Shape={}".format(a.ndim,a.shape))

Random Floating Values=[[[ 1.47649163 -0.65052292 -0.90791141]
  [-1.33270571  0.69700459 -0.38564257]
  [-2.25159343 -0.64684611  0.47764614]]

 [[-0.93400576  1.00754308  0.17322724]
  [-2.58352749 -1.9539825  -0.20385955]
  [-2.01647171  1.18677576  0.36196731]]] Type=<class 'numpy.ndarray'>
Dimension of a=3 Shape=(2, 3, 3)


In [16]:
from numpy import random as r
a=r.randn(2,2,2)
print("Random Floating Values={} Type={}".format(a,type(a)))
print("Dimension of a={} Shape={}".format(a.ndim,a.shape))

Random Floating Values=[[[ 0.29982215 -0.88417969]
  [-0.53135754 -0.50830397]]

 [[ 0.76091244  0.68731937]
  [-0.88575161  0.52602026]]] Type=<class 'numpy.ndarray'>
Dimension of a=3 Shape=(2, 2, 2)


In [17]:
#Syntax----varname=numpy.random.normal(loc=0,scale=1,size=None)

In [18]:
import numpy.random as r
a=r.normal()
print("Values={} Type={}".format(a,type(a)))

Values=-0.3637812989510126 Type=<class 'float'>


In [19]:
import numpy.random as r
a=r.normal()
print("Values={} Type={}".format(a,type(a)))

Values=-0.47407262568251146 Type=<class 'float'>


In [20]:
import numpy.random as r
a=r.normal()
print("Values={} Type={}".format(a,type(a)))

Values=0.8655187959936561 Type=<class 'float'>


In [21]:
import numpy.random as r
a=r.normal(2)
print("Values={} Type={}".format(a,type(a)))

Values=0.6941748098212435 Type=<class 'float'>


In [22]:
import numpy.random as r
a=r.normal(2)
print("Values={} Type={}".format(a,type(a)))

Values=1.8967917288410296 Type=<class 'float'>


In [24]:
for i in range(0,6):
    a=r.normal(2)
    print("Values={} Type={}".format(a,type(a)))

Values=1.2407525198404636 Type=<class 'float'>
Values=1.009489921778918 Type=<class 'float'>
Values=3.901487636934103 Type=<class 'float'>
Values=0.46349816843985736 Type=<class 'float'>
Values=1.4598538086573938 Type=<class 'float'>
Values=2.366277678003932 Type=<class 'float'>


In [25]:
for i in range(0,6):
    a=r.normal(6)
    print("Values={} Type={}".format(a,type(a)))

Values=3.9943311116584326 Type=<class 'float'>
Values=6.523262812964678 Type=<class 'float'>
Values=7.649515845254024 Type=<class 'float'>
Values=5.228897851727809 Type=<class 'float'>
Values=7.287952958654831 Type=<class 'float'>
Values=5.672311433979051 Type=<class 'float'>


In [26]:
import numpy as np
a=np.random.normal(2,2.5)
print("Values={} Type={}".format(a,type(a)))

Values=2.3497254536053034 Type=<class 'float'>


In [27]:
import numpy as np
a=np.random.normal(2,2.5)
print("Values={} Type={}".format(a,type(a)))

Values=0.28180791073232125 Type=<class 'float'>


In [28]:
for i in range(1,6):
    a=np.random.normal(2,2.5)
    print("Values={} Type={}".format(a,type(a)))

Values=1.9313959957863815 Type=<class 'float'>
Values=4.799818666961377 Type=<class 'float'>
Values=4.975849667273032 Type=<class 'float'>
Values=1.3847653520263643 Type=<class 'float'>
Values=1.041076738947921 Type=<class 'float'>
