In [1]:
#Syntax-1----varnma=numpy.random.randint(Value)--------->Random Number form 0 to 1

In [2]:
import numpy.random as r
a=r.randint(10)
print("Random Value={} Type={}".format(a,type(a)))

Random Value=7 Type=<class 'int'>


In [3]:
import numpy.random as r
a=r.randint(10)
print("Random Value={} Type={}".format(a,type(a)))

Random Value=5 Type=<class 'int'>


In [4]:
import numpy.random as r
a=r.randint(100)
print("Random Value={} Type={}".format(a,type(a)))

Random Value=46 Type=<class 'int'>


In [5]:
import numpy.random as r
a=r.randint(1000)
print("Random Value={} Type={}".format(a,type(a)))

Random Value=812 Type=<class 'int'>


In [6]:
#Generate 5 Random Values With Above Syntax
for i in range(0,6):
    a=r.randint(10)
    print("Random Value={} Type={}".format(a,type(a)))

Random Value=5 Type=<class 'int'>
Random Value=8 Type=<class 'int'>
Random Value=3 Type=<class 'int'>
Random Value=8 Type=<class 'int'>
Random Value=4 Type=<class 'int'>
Random Value=5 Type=<class 'int'>


In [7]:
#Syntax-2----varnma=numpy.random.randint(low,high)--------->Random Number form Low to High

In [8]:
import numpy.random as r
a=r.randint(1000,10000)
print("Random Value={} Type={}".format(a,type(a)))

Random Value=5921 Type=<class 'int'>


In [9]:
import numpy.random as r
a=r.randint(10000,100000)
print("Random Value={} Type={}".format(a,type(a)))

Random Value=35797 Type=<class 'int'>


In [11]:
import numpy.random as r
a=r.randint(1000,10000)
print("G-Mail Verification Code="+str(a))

G-Mail Verification Code=7585


In [12]:
#Syntax-3----varname=numpy.random.randint(low,high,size)

In [13]:
import numpy.random as r
a=r.randint(1000,10000,5)
print("Random Values={} Type={}".format(a,type(a)))
print("Dimension of a={} Shape={}".format(a.ndim,a.shape))

Random Values=[3349 8654 5884 2778 5891] Type=<class 'numpy.ndarray'>
Dimension of a=1 Shape=(5,)


In [16]:
import numpy.random as r
a=r.randint(1000,2000,10)
print("Random Values={} Type={}".format(a,type(a)))
print("Dimension of a={} Shape={}".format(a.ndim,a.shape))

Random Values=[1837 1204 1861 1744 1412 1428 1303 1121 1172 1223] Type=<class 'numpy.ndarray'>
Dimension of a=1 Shape=(10,)


In [17]:
#Creating for 2 Dimension array
import numpy.random as r
a=r.randint(1000,2000,(2,2))
print("Random Values={} Type={}".format(a,type(a)))
print("Dimension of a={} Shape={}".format(a.ndim,a.shape))

Random Values=[[1079 1504]
 [1301 1883]] Type=<class 'numpy.ndarray'>
Dimension of a=2 Shape=(2, 2)


In [18]:
#Creating for 2 Dimension array
import numpy.random as r
a=r.randint(1000,2000,(3,4))
print("Random Values={} Type={}".format(a,type(a)))
print("Dimension of a={} Shape={}".format(a.ndim,a.shape))

Random Values=[[1319 1030 1953 1296]
 [1156 1506 1530 1739]
 [1486 1387 1576 1645]] Type=<class 'numpy.ndarray'>
Dimension of a=2 Shape=(3, 4)


In [20]:
print("Number of Rows={}".format(a.shape[0]))
print("Number of Columns={}".format(a.shape[1]))

Number of Rows=3
Number of Columns=4


In [21]:
#Creating For 3 Dimension
from numpy import random as r
a=r.randint(1000,2000,(2,3,3))
print("Random Values={} Type={}".format(a,type(a)))
print("Dimension of a={} Shape={}".format(a.ndim,a.shape))

Random Values=[[[1157 1081 1274]
  [1458 1527 1304]
  [1160 1999 1070]]

 [[1937 1425 1186]
  [1801 1528 1267]
  [1265 1285 1736]]] Type=<class 'numpy.ndarray'>
Dimension of a=3 Shape=(2, 3, 3)


In [24]:
#Creating For 4 Dimension
from numpy import random as r
a=r.randint(1000,2000,(2,2,2,2))
print("Random Values={} Type={}".format(a,type(a)))
print("Dimesion of a={} Shape={}".format(a.ndim,a.shape))

Random Values=[[[[1505 1591]
   [1027 1656]]

  [[1120 1804]
   [1801 1679]]]


 [[[1920 1373]
   [1774 1558]]

  [[1074 1360]
   [1209 1001]]]] Type=<class 'numpy.ndarray'>
Dimesion of a=4 Shape=(2, 2, 2, 2)


In [25]:
print("Number of Matrices={}".format(a.shape[0]))
print("Number of Rows={}".format(a.shape[1]))
print("Number of Columns={}".format(a.shape[2]))

Number of Matrices=2
Number of Rows=2
Number of Columns=2
