In [1]:
#Syntax: varname=numpy.split(1DArray,EqualParts)

In [3]:
#Splitting the 1d Array Data with Equal Splits---numpy.split()
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
print("Original Array Data")
print(a)
#Split the above 1D Array into 2 parts
parts=np.split(a,2)
print(parts,type(parts))
print("First Part of 1d Array={} Type={}".format(parts[0],type(parts[0])))
print("Second Part of 1d Array={} Type={}".format(parts[1],type(parts[1])))

Original Array Data
[10 20 30 40 50 60 70 80]
[array([10, 20, 30, 40]), array([50, 60, 70, 80])] <class 'list'>
First Part of 1d Array=[10 20 30 40] Type=<class 'numpy.ndarray'>
Second Part of 1d Array=[50 60 70 80] Type=<class 'numpy.ndarray'>


In [4]:
#OR Another Method for 1d Array 
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
print("Original Array Data")
print(a)
#Split the above 1D Array into 2 parts
parts=np.split(a,2)
for part in parts:
    print("Part={} Type={}".format(part,type(part)))

Original Array Data
[10 20 30 40 50 60 70 80]
Part=[10 20 30 40] Type=<class 'numpy.ndarray'>
Part=[50 60 70 80] Type=<class 'numpy.ndarray'>


In [6]:
#OR Another Method for 1d Array
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
print("Original Array Data")
print(a)
#Split the above 1D Array into 4 parts
parts=np.split(a,4)
print(parts,type(parts))
for part in parts:
    print("Part={} Type={}".format(part,type(part)))

Original Array Data
[10 20 30 40 50 60 70 80]
[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80])] <class 'list'>
Part=[10 20] Type=<class 'numpy.ndarray'>
Part=[30 40] Type=<class 'numpy.ndarray'>
Part=[50 60] Type=<class 'numpy.ndarray'>
Part=[70 80] Type=<class 'numpy.ndarray'>


In [7]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("Original 1D Array Data")
print(a) # [10 20 30 50 60 70 80 90]
#Split the above 1d Array into 4 Parts
print("-------------------------------------------")
#parts1d=np.split(a,4)---ValueError: array split does not result in an equal division

Original 1D Array Data
[10 20 30 40 50 60 70 80 90]
-------------------------------------------


In [8]:
#Syntax: varname=numpy.array_split(1DArray,Parts)

In [9]:
#Splitting the 1d Array Data with Equal or unequal Splits---numpy.array_split()
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("Original Array Data")
print(a)
parts=np.array_split(a,2)
print(parts,type(parts))
print("First Part of 1d Array={} Type={}".format(parts[0],type(parts[0])))
print("Second Part of 1d Array={} Type={}".format(parts[1],type(parts[1])))

Original Array Data
[10 20 30 40 50 60 70 80 90]
[array([10, 20, 30, 40, 50]), array([60, 70, 80, 90])] <class 'list'>
First Part of 1d Array=[10 20 30 40 50] Type=<class 'numpy.ndarray'>
Second Part of 1d Array=[60 70 80 90] Type=<class 'numpy.ndarray'>


In [11]:
#Or Another Method for 2D Array
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90])
print("Original Array Data")
print(a)
parts=np.array_split(a,4)
print(parts,type(parts))
for part in parts:
    print("Part={} Type={}".format(part,type(part)))

Original Array Data
[10 20 30 40 50 60 70 80 90]
[array([10, 20, 30]), array([40, 50]), array([60, 70]), array([80, 90])] <class 'list'>
Part=[10 20 30] Type=<class 'numpy.ndarray'>
Part=[40 50] Type=<class 'numpy.ndarray'>
Part=[60 70] Type=<class 'numpy.ndarray'>
Part=[80 90] Type=<class 'numpy.ndarray'>


In [12]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,25])
print("Original 1D Array Data")
print(a)
#Split the above 1d Array into 5 Parts
parts1d=np.array_split(a,5)
print(parts1d,type(parts1d))
for part in parts1d:
    print("Part:{} Type={}".format(part,type(part)))

Original 1D Array Data
[10 20 30 40 50 60 70 80 90 25]
[array([10, 20]), array([30, 40]), array([50, 60]), array([70, 80]), array([90, 25])] <class 'list'>
Part:[10 20] Type=<class 'numpy.ndarray'>
Part:[30 40] Type=<class 'numpy.ndarray'>
Part:[50 60] Type=<class 'numpy.ndarray'>
Part:[70 80] Type=<class 'numpy.ndarray'>
Part:[90 25] Type=<class 'numpy.ndarray'>


In [13]:
#Syntax:  varname=numpy.split(2dArraydata, parts,axis)

In [14]:
#Splitting th 2D Array Data ------split()
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,25,35,45]).reshape(4,3)
print("Original Array Data")
print(a)
parts=np.split(a,2,axis=0)
for part in range(len(parts)):
    print("Part:{}: \n{} Type={}".format(part+1,parts[part],type(parts[part])))

Original Array Data
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [25 35 45]]
Part:1: 
[[10 20 30]
 [40 50 60]] Type=<class 'numpy.ndarray'>
Part:2: 
[[70 80 90]
 [25 35 45]] Type=<class 'numpy.ndarray'>


In [16]:
#Splitting th 2D Array Data ------split()
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,25,35,45]).reshape(4,3)
print("Original Array Data")
print(a)
parts=np.split(a,4,axis=0)
for part in range(len(parts)):
    print("Part:{}: \n{} Type={}".format(part+1,parts[part],type(parts[part])))

Original Array Data
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [25 35 45]]
Part:1: 
[[10 20 30]] Type=<class 'numpy.ndarray'>
Part:2: 
[[40 50 60]] Type=<class 'numpy.ndarray'>
Part:3: 
[[70 80 90]] Type=<class 'numpy.ndarray'>
Part:4: 
[[25 35 45]] Type=<class 'numpy.ndarray'>


In [17]:
#Splitting th 2D Array Data ------split()
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,25,35,45]).reshape(3,4)
print("Original Array Data")
print(a)
parts=np.split(a,2,axis=1)
for part in range(len(parts)):
    print("Part:{}: \n{} Type={}".format(part+1,parts[part],type(parts[part])))

Original Array Data
[[10 20 30 40]
 [50 60 70 80]
 [90 25 35 45]]
Part:1: 
[[10 20]
 [50 60]
 [90 25]] Type=<class 'numpy.ndarray'>
Part:2: 
[[30 40]
 [70 80]
 [35 45]] Type=<class 'numpy.ndarray'>


In [4]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,25,35,45]).reshape(3,4)
print("Original 2D Array Data")
print(a) 
parts=np.split(a,4,axis=1)
for part in range(len(parts)):
    print("Part{}:\n{} Type={}".format(part+1,parts[part],type(parts[part])))

Original 2D Array Data
[[10 20 30 40]
 [50 60 70 80]
 [90 25 35 45]]
Part1:
[[10]
 [50]
 [90]] Type=<class 'numpy.ndarray'>
Part2:
[[20]
 [60]
 [25]] Type=<class 'numpy.ndarray'>
Part3:
[[30]
 [70]
 [35]] Type=<class 'numpy.ndarray'>
Part4:
[[40]
 [80]
 [45]] Type=<class 'numpy.ndarray'>


In [5]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,25,35,45]).reshape(3,4)
print("Original 2D Array Data")
print(a) 
parts=np.array_split(a,2,axis=0)
for part in range(len(parts)):
    print("Part{}:\n{} Type={}".format(part+1,parts[part],type(parts[part])))

Original 2D Array Data
[[10 20 30 40]
 [50 60 70 80]
 [90 25 35 45]]
Part1:
[[10 20 30 40]
 [50 60 70 80]] Type=<class 'numpy.ndarray'>
Part2:
[[90 25 35 45]] Type=<class 'numpy.ndarray'>


In [1]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,25,35,45]).reshape(3,4)
print("Original Array Data")
print(a)
parts=np.array_split(a,2,axis=1)
for part in range(len(parts)):
    print("Part:{}: \n{} Type={}".format(part+1,parts[part],type(parts[part])))

Original Array Data
[[10 20 30 40]
 [50 60 70 80]
 [90 25 35 45]]
Part:1: 
[[10 20]
 [50 60]
 [90 25]] Type=<class 'numpy.ndarray'>
Part:2: 
[[30 40]
 [70 80]
 [35 45]] Type=<class 'numpy.ndarray'>


In [2]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,25,35,45]).reshape(3,4)
print("Original 2D Array Data")
print(a) 
parts=np.array_split(a,3,axis=1)
for part in range(len(parts)):
    print("Part{}:\n{} Type={}".format(part+1,parts[part],type(parts[part])))

Original 2D Array Data
[[10 20 30 40]
 [50 60 70 80]
 [90 25 35 45]]
Part1:
[[10 20]
 [50 60]
 [90 25]] Type=<class 'numpy.ndarray'>
Part2:
[[30]
 [70]
 [35]] Type=<class 'numpy.ndarray'>
Part3:
[[40]
 [80]
 [45]] Type=<class 'numpy.ndarray'>


In [3]:
#Syntax: varname=numpy.vsplit(2DArrayData, equalRowparts)

In [4]:
#Splitting 2D Array data with  vsplit()
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,25,35,45]).reshape(4,3)
print("Original Array Data")
print(a)
parts=np.vsplit(a,2)
for part in parts:
    print("Part:{} Type={}".format(part,type(part)))

Original Array Data
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [25 35 45]]
Part:[[10 20 30]
 [40 50 60]] Type=<class 'numpy.ndarray'>
Part:[[70 80 90]
 [25 35 45]] Type=<class 'numpy.ndarray'>


In [5]:
#Splitting 2D Array data with  vsplit()
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,25,35,45]).reshape(4,3)
print("Original Array Data")
print(a)
parts=np.vsplit(a,4)
for part in parts:
    print("Part:{} Type={}".format(part,type(part)))

Original Array Data
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [25 35 45]]
Part:[[10 20 30]] Type=<class 'numpy.ndarray'>
Part:[[40 50 60]] Type=<class 'numpy.ndarray'>
Part:[[70 80 90]] Type=<class 'numpy.ndarray'>
Part:[[25 35 45]] Type=<class 'numpy.ndarray'>


In [6]:
#Syntax: varname=numpy.hsplit(2DArrayData, equalColumnparts)

In [9]:
#Splitting 2D Array data with  hsplit()
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,25,35,45]).reshape(3,4)
print("Original Array Data")
print(a)
parts=np.hsplit(a,2)
for part in parts:
    print("Part\n{} Type={}".format(part,type(part)))

Original Array Data
[[10 20 30 40]
 [50 60 70 80]
 [90 25 35 45]]
Part
[[10 20]
 [50 60]
 [90 25]] Type=<class 'numpy.ndarray'>
Part
[[30 40]
 [70 80]
 [35 45]] Type=<class 'numpy.ndarray'>


In [10]:
#Splitting 2D Array data with  hsplit()
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,25,35,45]).reshape(3,4)
print("Original Array Data")
print(a)
parts=np.hsplit(a,4)
for part in parts:
    print("Part\n{} Type={}".format(part,type(part)))

Original Array Data
[[10 20 30 40]
 [50 60 70 80]
 [90 25 35 45]]
Part
[[10]
 [50]
 [90]] Type=<class 'numpy.ndarray'>
Part
[[20]
 [60]
 [25]] Type=<class 'numpy.ndarray'>
Part
[[30]
 [70]
 [35]] Type=<class 'numpy.ndarray'>
Part
[[40]
 [80]
 [45]] Type=<class 'numpy.ndarray'>


In [11]:
#Create an Object of 3D Array 
import numpy as np
a=np.arange(3*3*3).reshape(3,3,3)
print("Original 2D Array Data")
print(a) 
#depthparts=np.dsplit(a,2)---ValueError: array split does not result in an equal division

Original 2D Array Data
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [12]:
#Create an Object of 3D Array
import numpy as np
a=np.arange(3*4*4).reshape(3,4,4)
print("Original Array Data")
print(a)
depthparts=np.dsplit(a,2)
for part in depthparts:
    print("part\n{} Type={}".format(part,type(part)))

Original Array Data
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
part
[[[ 0  1]
  [ 4  5]
  [ 8  9]
  [12 13]]

 [[16 17]
  [20 21]
  [24 25]
  [28 29]]

 [[32 33]
  [36 37]
  [40 41]
  [44 45]]] Type=<class 'numpy.ndarray'>
part
[[[ 2  3]
  [ 6  7]
  [10 11]
  [14 15]]

 [[18 19]
  [22 23]
  [26 27]
  [30 31]]

 [[34 35]
  [38 39]
  [42 43]
  [46 47]]] Type=<class 'numpy.ndarray'>


In [13]:
len(depthparts)

2

In [15]:
#Create an Object of 3D Array
import numpy as np
a=np.arange(3*4*4).reshape(3,4,4)
print("original Array Data")
print(a)
depthparts=np.split(a,2,axis=2)
for part in depthparts:
    print("Part\n{} Type={}".format(part,type(part)))

original Array Data
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
Part
[[[ 0  1]
  [ 4  5]
  [ 8  9]
  [12 13]]

 [[16 17]
  [20 21]
  [24 25]
  [28 29]]

 [[32 33]
  [36 37]
  [40 41]
  [44 45]]] Type=<class 'numpy.ndarray'>
Part
[[[ 2  3]
  [ 6  7]
  [10 11]
  [14 15]]

 [[18 19]
  [22 23]
  [26 27]
  [30 31]]

 [[34 35]
  [38 39]
  [42 43]
  [46 47]]] Type=<class 'numpy.ndarray'>


In [16]:
#Create an Object of 3D Array
import numpy as np
a=np.arange(3*4*4).reshape(3,4,4)
print("Original Array Data")
print(a)
depthparts=np.array_split(a,3,axis=2)
for part in depthparts:
    print("Part\n{} Type={}".format(part,type(part)))

Original Array Data
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
Part
[[[ 0  1]
  [ 4  5]
  [ 8  9]
  [12 13]]

 [[16 17]
  [20 21]
  [24 25]
  [28 29]]

 [[32 33]
  [36 37]
  [40 41]
  [44 45]]] Type=<class 'numpy.ndarray'>
Part
[[[ 2]
  [ 6]
  [10]
  [14]]

 [[18]
  [22]
  [26]
  [30]]

 [[34]
  [38]
  [42]
  [46]]] Type=<class 'numpy.ndarray'>
Part
[[[ 3]
  [ 7]
  [11]
  [15]]

 [[19]
  [23]
  [27]
  [31]]

 [[35]
  [39]
  [43]
  [47]]] Type=<class 'numpy.ndarray'>


In [17]:
#Create 3D Array 
import numpy as np
a=np.arange(3*4*3).reshape(3,4,3)
print("Original 2D Array Data")
print(a) 
depthparts=np.array_split(a,2,axis=2)
for part in depthparts:
    print("Part:\n{}  Type:{}".format(part,type(part)))

Original 2D Array Data
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]
Part:
[[[ 0  1]
  [ 3  4]
  [ 6  7]
  [ 9 10]]

 [[12 13]
  [15 16]
  [18 19]
  [21 22]]

 [[24 25]
  [27 28]
  [30 31]
  [33 34]]]  Type:<class 'numpy.ndarray'>
Part:
[[[ 2]
  [ 5]
  [ 8]
  [11]]

 [[14]
  [17]
  [20]
  [23]]

 [[26]
  [29]
  [32]
  [35]]]  Type:<class 'numpy.ndarray'>


In [19]:
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [20]:
print(a[:,:,:2])
print("-------------------------")
print(a[:,:,2:])

[[[ 0  1]
  [ 3  4]
  [ 6  7]
  [ 9 10]]

 [[12 13]
  [15 16]
  [18 19]
  [21 22]]

 [[24 25]
  [27 28]
  [30 31]
  [33 34]]]
-------------------------
[[[ 2]
  [ 5]
  [ 8]
  [11]]

 [[14]
  [17]
  [20]
  [23]]

 [[26]
  [29]
  [32]
  [35]]]
