In [3]:
#Create an Object of List
import sys
lst=[10,20,30,40,50,60]
print("Content of lst={} Type={}".format(lst,type(lst)))
print("Memory of Traditional Python List=",sys.getsizeof(lst))

Content of lst=[10, 20, 30, 40, 50, 60] Type=<class 'list'>
Memory of Traditional Python List= 104


In [11]:
#Convert Traditional Python List into ndarray list
import numpy as np
lst=[10,20,30,40,50,60]
print("Content of lst=",lst)
a=np.array(lst)
print("Content of a={} Type={}".format(a,type(a)))
print("Memory of ndarray=",sys.getsizeof(a))

Content of lst= [10, 20, 30, 40, 50, 60]
Content of a=[10 20 30 40 50 60] Type=<class 'numpy.ndarray'>
Memory of ndarray= 160


In [30]:
#Create an Object of list
import sys
lst=[10,20,30,40,50,60,70,15,23,56,78,90,34,66,89,123,45,78,30,40,50,60,70,80,40,20,20,30,40,40,40,50,60,70,80,90]
print(len(lst))
print("Content of lst=",lst)
print("Memory of Traditional Python List=",sys.getsizeof(lst))

36
Content of lst= [10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 30, 40, 50, 60, 70, 80, 40, 20, 20, 30, 40, 40, 40, 50, 60, 70, 80, 90]
Memory of Traditional Python List= 376


In [29]:
#Convert Traditional Python List into ndarray list
import numpy as np
lst=[10,20,30,40,50,60,70,15,23,56,78,90,34,66,89,123,45,78,30,40,50,60,70,80,40,20,20,30,40,40,40,50,60,70,80,90]
print(len(lst))
print("Content of lst=",lst)
a=np.array(lst)
print("Content of a={} Type={}".format(a,type(a)))
print("Memory Space of ndarray=",sys.getsizeof(a))

36
Content of lst= [10, 20, 30, 40, 50, 60, 70, 15, 23, 56, 78, 90, 34, 66, 89, 123, 45, 78, 30, 40, 50, 60, 70, 80, 40, 20, 20, 30, 40, 40, 40, 50, 60, 70, 80, 90]
Content of a=[ 10  20  30  40  50  60  70  15  23  56  78  90  34  66  89 123  45  78
  30  40  50  60  70  80  40  20  20  30  40  40  40  50  60  70  80  90] Type=<class 'numpy.ndarray'>
Memory Space of ndarray= 400


In [31]:
#Create an Object of List---Memory Address
import sys
lst=[10,20,30,40,50,60,70,15,23,56,78,90,34,66,89,13,45,78]
for val in lst:
    print("Value={} Address of Value={} Address of lst={}".format(val,id(val),id(lst)))

Value=10 Address of Value=140723563259288 Address of lst=2919889000448
Value=20 Address of Value=140723563259608 Address of lst=2919889000448
Value=30 Address of Value=140723563259928 Address of lst=2919889000448
Value=40 Address of Value=140723563260248 Address of lst=2919889000448
Value=50 Address of Value=140723563260568 Address of lst=2919889000448
Value=60 Address of Value=140723563260888 Address of lst=2919889000448
Value=70 Address of Value=140723563261208 Address of lst=2919889000448
Value=15 Address of Value=140723563259448 Address of lst=2919889000448
Value=23 Address of Value=140723563259704 Address of lst=2919889000448
Value=56 Address of Value=140723563260760 Address of lst=2919889000448
Value=78 Address of Value=140723563261464 Address of lst=2919889000448
Value=90 Address of Value=140723563261848 Address of lst=2919889000448
Value=34 Address of Value=140723563260056 Address of lst=2919889000448
Value=66 Address of Value=140723563261080 Address of lst=2919889000448
Value=

In [32]:
#Create an Object of list and Convert it into ndarray---Memory Address
import sys
lst=[10,20,30,40,50,60,70,15,23,56,78,90,34,66,89,13,45,78]
#Convert list into ndarray object
a=np.array(lst)
for val in a:
    print("Value={} Address of Value={} Address of a={}".format(val,id(val),id(a)))

Value=10 Address of Value=2919892104080 Address of a=2919892708848
Value=20 Address of Value=2919892104144 Address of a=2919892708848
Value=30 Address of Value=2919892104080 Address of a=2919892708848
Value=40 Address of Value=2919892103568 Address of a=2919892708848
Value=50 Address of Value=2919892104080 Address of a=2919892708848
Value=60 Address of Value=2919892103568 Address of a=2919892708848
Value=70 Address of Value=2919892104080 Address of a=2919892708848
Value=15 Address of Value=2919892103568 Address of a=2919892708848
Value=23 Address of Value=2919892104080 Address of a=2919892708848
Value=56 Address of Value=2919892103568 Address of a=2919892708848
Value=78 Address of Value=2919892104080 Address of a=2919892708848
Value=90 Address of Value=2919892103568 Address of a=2919892708848
Value=34 Address of Value=2919892104080 Address of a=2919892708848
Value=66 Address of Value=2919892103568 Address of a=2919892708848
Value=89 Address of Value=2919892104080 Address of a=291989270

In [33]:
#Vector Based Operations
lst=[10,20,30,40]
print("Content of lst={} Type={}".format(lst,type(lst)))
#Increase Every Value of lst by 1
lst=lst+1

Content of lst=[10, 20, 30, 40] Type=<class 'list'>


TypeError: can only concatenate list (not "int") to list

In [34]:
#Vector Based Operations Not Possible By Default-
#Then How do u Get It on List---Vector Based Operations
lst=[10,20,30,40]
print("Content of lst={} Type={}".format(lst,type(lst)))
for i in range(len(lst)):
    lst[i]=lst[i]+1
print("Content of lst={} Type={}".format(lst,type(lst)))

Content of lst=[10, 20, 30, 40] Type=<class 'list'>
Content of lst=[11, 21, 31, 41] Type=<class 'list'>


In [35]:
#Vector Based Operations Using ndarray Object
lst=[10,20,30,40]
print("Content of lst={} Type={}".format(lst,type(lst)))
#Convert the list Object into ndarray Object
a=np.array(lst)
print("Content of a={} Type={}".format(a,type(a)))
a=a+1   #Vector Based Operation
print("Content of a={} Type={}".format(a,type(a)))

Content of lst=[10, 20, 30, 40] Type=<class 'list'>
Content of a=[10 20 30 40] Type=<class 'numpy.ndarray'>
Content of a=[11 21 31 41] Type=<class 'numpy.ndarray'>


In [36]:
#Re-Shaping Mechanism in List
lst=[10,20,30,40]
print("Content of lst={} Type={}".format(lst,type(lst)))
lst.reshape(3,4)

Content of lst=[10, 20, 30, 40] Type=<class 'list'>


AttributeError: 'list' object has no attribute 'reshape'

In [39]:
#To Reshape the Content of Traditional Python Iterable Object,
#We Must Convert Traditional Python Iterable Object into ndarray
lst=[10,20,30,40,50,60,70,80,90,15,25,35]
print("Content of lst={} Type={}".format(lst,type(lst)))
#Create list into ndarray
a=np.array(lst)
print("Content of a={} Type={}".format(a,type(a)))

Content of lst=[10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 25, 35] Type=<class 'list'>
Content of a=[10 20 30 40 50 60 70 80 90 15 25 35] Type=<class 'numpy.ndarray'>


In [40]:
#How to See Dimensions of these
print("Dimensions of ndarray=",a.ndim)

Dimensions of ndarray= 1


In [43]:
#ReShape ndarray Object in 2-Dimension
a.shape=(4,3)
print("Content of a")
print(a)
print("Dimension of a=",a.ndim)

Content of a
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 25 35]]
Dimension of a= 2


In [44]:
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [15, 25, 35]])

In [45]:
a.ndim

2

In [46]:
a.shape=(6,2)
print("Content of a")
print(a)
print("Dimension of a=",a.ndim)

Content of a
[[10 20]
 [30 40]
 [50 60]
 [70 80]
 [90 15]
 [25 35]]
Dimension of a= 2


In [47]:
a.shape=(2,6)
print("Content of a")
print(a)
print("Dimension of a=",a.ndim)

Content of a
[[10 20 30 40 50 60]
 [70 80 90 15 25 35]]
Dimension of a= 2


In [49]:
#Reshaping ndarray Object into 3-Dimensional
a.shape=(2,3,2)
print("Content of a")
print(a)
print("Dimenison of a=",a.ndim)

Content of a
[[[10 20]
  [30 40]
  [50 60]]

 [[70 80]
  [90 15]
  [25 35]]]
Dimenison of a= 3


In [50]:
a=np.arange(16).reshape(2,2,2,2)
print("Content of a")
print(a)
print("Dimension of a=",a.ndim)

Content of a
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
Dimension of a= 4


In [53]:
a.shape=(16,)

In [54]:
print("Content of a")
print(a)
print("Dimension of a=",a.ndim)

Content of a
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Dimension of a= 1
