In [4]:
#Code for Building  a Matrix with dim of 2 with All entries as 0
import numpy as np
lst=[0,0,0,0]
a=np.array(lst)
print("Zero Matrix")
print(a)
print("Dimension of ndarray = {}".format(a.ndim))

Zero Matrix
[0 0 0 0]
Dimension of ndarray = 1


In [5]:
#Code for Building a Matrix with dim of 2 Dim With All entries as 0
import numpy as np
lst=[[0,0,0],[0,0,0],[0,0,0]]
a=np.array(lst)
print("Zero Matrix")
print(a)
print("Dimension of ndarray = {}".format(a.ndim))

Zero Matrix
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Dimension of ndarray = 2


In [6]:
#Syntax---varname=numpy.zeros(shape,dtype)----zeros()
#Create an Object of ndarray with 6 zeros
import numpy as np
a=np.zeros(6)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of ndarray = {}".format(a.ndim))

Content of a=[0. 0. 0. 0. 0. 0.] Type=<class 'numpy.ndarray'>
Dimension of ndarray = 1


In [7]:
#Create an Object of ndarray with 6 zeros---zeros()
import numpy as np
a=np.zeros(6,dtype=int)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of ndarray={}".format(a.ndim))

Content of a=[0 0 0 0 0 0] Type=<class 'numpy.ndarray'>
Dimension of ndarray=1


In [8]:
#Create an Object of ndarray with dim 2 and with 9 zeros---zeros()
import numpy as np
a=np.zeros((3,3))
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of ndarray={}".format(a.ndim))

Content of a=[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] Type=<class 'numpy.ndarray'>
Dimension of ndarray=2


In [10]:
#Create an Object of ndarray with dim 2 and with 9 zeros---zeros()
import numpy as np
a=np.zeros((3,3),dtype=int)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of ndarray={}".format(a.ndim))

Content of a=[[0 0 0]
 [0 0 0]
 [0 0 0]] Type=<class 'numpy.ndarray'>
Dimension of ndarray=2


In [11]:
#Create an Object of ndarray with dim 3 and with 12 zeros----zeros()
import numpy as np
a=np.zeros((2,3,2),dtype=int)
print("Content of a\n{} Type={}".format(a,type(a)))
print("Dimension of ndarray={}".format(a.ndim))

Content of a
[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]] Type=<class 'numpy.ndarray'>
Dimension of ndarray=3


In [12]:
#Syntax--varname=numpy.ones(shape,dtype)---ones()
#Create an Object of ndarray with 6 ones
import numpy as np
a=np.ones(6)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of ndarray={}".format(a.ndim))

Content of a=[1. 1. 1. 1. 1. 1.] Type=<class 'numpy.ndarray'>
Dimension of ndarray=1


In [13]:
#Create an Object of ndarray with 6 ones----ones()
import numpy as np
a=np.ones(6,dtype=int)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of ndarray={}".format(a.ndim))

Content of a=[1 1 1 1 1 1] Type=<class 'numpy.ndarray'>
Dimension of ndarray=1


In [14]:
#Create an Object of ndarray with 9 ones as 2 dim----ones()
import numpy as np
a=np.ones((3,3),int)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of ndarray={}".format(a.ndim))

Content of a=[[1 1 1]
 [1 1 1]
 [1 1 1]] Type=<class 'numpy.ndarray'>
Dimension of ndarray=2


In [15]:
#Create an Object of ndarray with 18 Ones as 3 dim----ones()
import numpy as np
a=np.ones((2,3,3),int)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of ndarray={}".format(a.ndim))

Content of a=[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]] Type=<class 'numpy.ndarray'>
Dimension of ndarray=3


In [16]:
#Syntax---varname(shape,fill_value,dtype)----full()
#Create an Object of ndarray with 6 Entries as 3 dim ----full()
import numpy as np
a=np.full(6,3)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of ndarray={}".format(a.ndim))

Content of a=[3 3 3 3 3 3] Type=<class 'numpy.ndarray'>
Dimension of ndarray=1


In [19]:
#Create an Object of ndarray with 6 Entries as 3 dim -----full()
import numpy as np
a=np.full(6,3,dtype=float)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of ndarray={}".format(a.ndim))

Content of a=[3. 3. 3. 3. 3. 3.] Type=<class 'numpy.ndarray'>
Dimension of ndarray=1


In [20]:
#Create an Object of ndarray with 6 Entries as 3 dim -----full()
import numpy as np
a=np.full(shape=6,fill_value=3,dtype=float)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of ndarray={}".format(a.ndim))

Content of a=[3. 3. 3. 3. 3. 3.] Type=<class 'numpy.ndarray'>
Dimension of ndarray=1


In [21]:
#Create an object of ndarray with 6 Entries as 9 with 2D
import numpy as np
a=np.full(shape=(3,3),fill_value=9)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of ndarray={}".format(a.ndim))

Content of a=[[9 9 9]
 [9 9 9]
 [9 9 9]] Type=<class 'numpy.ndarray'>
Dimension of ndarray=2


In [22]:
#Create an object of ndarray with 12 Entries as 8 with 3D
import numpy as np
a=np.full(shape=(2,3,2),fill_value=8)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of ndarray={}".format(a.ndim))

Content of a=[[[8 8]
  [8 8]
  [8 8]]

 [[8 8]
  [8 8]
  [8 8]]] Type=<class 'numpy.ndarray'>
Dimension of ndarray=3


In [1]:
#Syntax--varname=numpy.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype)
#Create an Object of linspace() to Execute this Function
import numpy as np
a=np.linspace(0,10)
print("Content of a={} Type={}".format(a,type(a)))

Content of a=[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ] Type=<class 'numpy.ndarray'>


In [2]:
len(a)

50

In [3]:
#Create an Object of linspace() to Execute this Function
import numpy as np
a=np.linspace(0,10,endpoint=False)
print("Content of a={} Type={}".format(a,type(a)))

Content of a=[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8] Type=<class 'numpy.ndarray'>


In [4]:
len(a)

50

In [5]:
#Create an Object of linspace() to Execute this Function
import numpy as np
a=np.linspace(0,10,num=10)
print("Content of a={} Type={}".format(a,type(a)))

Content of a=[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ] Type=<class 'numpy.ndarray'>


In [6]:
len(a)

10

In [7]:
#Create an Object of linspace() to Execute this Function
import numpy as np
a=np.linspace(0,10,num=10,endpoint=False)
print("Content of a={} Type={}".format(a,type(a)))

Content of a=[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] Type=<class 'numpy.ndarray'>


In [8]:
len(a)

10

In [9]:
#Create an Object of linspace() to Execute this Function
import numpy as np
a=np.linspace(0,10,num=10,retstep=True)
print("Content of a={} Type={}".format(a[0],type(a[0])))
print("Return Step of a={} Type={}".format(a[1],type(a[1])))

Content of a=[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ] Type=<class 'numpy.ndarray'>
Return Step of a=1.1111111111111112 Type=<class 'numpy.float64'>


In [10]:
#Create an Object Using linspace()
import numpy as np
a,rst=np.linspace(0,10,num=10,retstep=True)
print("Content of a={} Type={}".format(a,type(a)))
print("Return Step of rst={} Type={}".format(rst,type(rst)))

Content of a=[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ] Type=<class 'numpy.ndarray'>
Return Step of rst=1.1111111111111112 Type=<class 'numpy.float64'>


In [12]:
#Create an Object Using linspace()
import numpy as np
a,rst=np.linspace(0,10,num=20,retstep=True)
print("Content of a={} Type={}".format(a,type(a)))
print("Return Step of rst={} Type={}".format(rst,type(rst)))

Content of a=[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ] Type=<class 'numpy.ndarray'>
Return Step of rst=0.5263157894736842 Type=<class 'numpy.float64'>


In [13]:
len(a)

20

In [15]:
#Syntax---varname=numpy.identity(N,dtype)
#Create an Object Using identity() Function
import numpy as np
a=np.identity(2)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimensiion of a={} Type={}".format(a.ndim,type(a)))

Content of a=[[1. 0.]
 [0. 1.]] Type=<class 'numpy.ndarray'>
Dimensiion of a=2 Type=<class 'numpy.ndarray'>


In [16]:
#Create an Identity Matrix with 2D
import numpy as np
a=np.identity(2,int)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of a={}".format(a.ndim))

Content of a=[[1 0]
 [0 1]] Type=<class 'numpy.ndarray'>
Dimension of a=2


In [17]:
#Create an Identity Matrix with 3D
import numpy as np
a=np.identity(3,int)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of a={}".format(a.ndim))

Content of a=[[1 0 0]
 [0 1 0]
 [0 0 1]] Type=<class 'numpy.ndarray'>
Dimension of a=2


In [18]:
#Create an Identity Matrix with 3D
import numpy as np
a=np.identity(4,int)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of a={}".format(a.ndim))

Content of a=[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] Type=<class 'numpy.ndarray'>
Dimension of a=2


In [19]:
#Create an Identity Matrix with 3D
import numpy as np
a=np.identity(6,int)
print("Content of a={} Type={}".format(a,type(a)))
print("Dimension of a={}".format(a.ndim))

Content of a=[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]] Type=<class 'numpy.ndarray'>
Dimension of a=2
